// Auto-generated by gen_tb.py. Do not edit by hand.
`timescale 1ns/1ps

module tb_vlm_engine_v4_system_liveness;
    localparam ap_ST_fsm_state1 = 64'd1;
    localparam ap_ST_fsm_state2 = 64'd2;
    localparam ap_ST_fsm_state3 = 64'd4;
    localparam ap_ST_fsm_state4 = 64'd8;
    localparam ap_ST_fsm_state5 = 64'd16;
    localparam ap_ST_fsm_state6 = 64'd32;
    localparam ap_ST_fsm_state7 = 64'd64;
    localparam ap_ST_fsm_state8 = 64'd128;
    localparam ap_ST_fsm_state9 = 64'd256;
    localparam ap_ST_fsm_state10 = 64'd512;
    localparam ap_ST_fsm_state11 = 64'd1024;
    localparam ap_ST_fsm_state12 = 64'd2048;
    localparam ap_ST_fsm_state13 = 64'd4096;
    localparam ap_ST_fsm_state14 = 64'd8192;
    localparam ap_ST_fsm_state15 = 64'd16384;
    localparam ap_ST_fsm_state16 = 64'd32768;
    localparam ap_ST_fsm_state17 = 64'd65536;
    localparam ap_ST_fsm_state18 = 64'd131072;
    localparam ap_ST_fsm_state19 = 64'd262144;
    localparam ap_ST_fsm_state20 = 64'd524288;
    localparam ap_ST_fsm_state21 = 64'd1048576;
    localparam ap_ST_fsm_state22 = 64'd2097152;
    localparam ap_ST_fsm_state23 = 64'd4194304;
    localparam ap_ST_fsm_state24 = 64'd8388608;
    localparam ap_ST_fsm_state25 = 64'd16777216;
    localparam ap_ST_fsm_state26 = 64'd33554432;
    localparam ap_ST_fsm_state27 = 64'd67108864;
    localparam ap_ST_fsm_state28 = 64'd134217728;
    localparam ap_ST_fsm_state29 = 64'd268435456;
    localparam ap_ST_fsm_state30 = 64'd536870912;
    localparam ap_ST_fsm_state31 = 64'd1073741824;
    localparam ap_ST_fsm_state32 = 64'd2147483648;
    localparam ap_ST_fsm_state33 = 64'd4294967296;
    localparam ap_ST_fsm_state34 = 64'd8589934592;
    localparam ap_ST_fsm_state35 = 64'd17179869184;
    localparam ap_ST_fsm_state36 = 64'd34359738368;
    localparam ap_ST_fsm_state37 = 64'd68719476736;
    localparam ap_ST_fsm_state38 = 64'd137438953472;
    localparam ap_ST_fsm_state39 = 64'd274877906944;
    localparam ap_ST_fsm_state40 = 64'd549755813888;
    localparam ap_ST_fsm_state41 = 64'd1099511627776;
    localparam ap_ST_fsm_state42 = 64'd2199023255552;
    localparam ap_ST_fsm_state43 = 64'd4398046511104;
    localparam ap_ST_fsm_state44 = 64'd8796093022208;
    localparam ap_ST_fsm_state45 = 64'd17592186044416;
    localparam ap_ST_fsm_state46 = 64'd35184372088832;
    localparam ap_ST_fsm_state47 = 64'd70368744177664;
    localparam ap_ST_fsm_state48 = 64'd140737488355328;
    localparam ap_ST_fsm_state49 = 64'd281474976710656;
    localparam ap_ST_fsm_state50 = 64'd562949953421312;
    localparam ap_ST_fsm_state51 = 64'd1125899906842624;
    localparam ap_ST_fsm_state52 = 64'd2251799813685248;
    localparam ap_ST_fsm_state53 = 64'd4503599627370496;
    localparam ap_ST_fsm_state54 = 64'd9007199254740992;
    localparam ap_ST_fsm_state55 = 64'd18014398509481984;
    localparam ap_ST_fsm_state56 = 64'd36028797018963968;
    localparam ap_ST_fsm_state57 = 64'd72057594037927936;
    localparam ap_ST_fsm_state58 = 64'd144115188075855872;
    localparam ap_ST_fsm_state59 = 64'd288230376151711744;
    localparam ap_ST_fsm_state60 = 64'd576460752303423488;
    localparam ap_ST_fsm_state61 = 64'd1152921504606846976;
    localparam ap_ST_fsm_state62 = 64'd2305843009213693952;
    localparam ap_ST_fsm_state63 = 64'd4611686018427387904;
    localparam ap_ST_fsm_state64 = 64'd9223372036854775808;
    localparam C_S_AXI_CONTROL_DATA_WIDTH = 32;
    localparam C_S_AXI_CONTROL_ADDR_WIDTH = 7;
    localparam C_S_AXI_DATA_WIDTH = 32;
    localparam C_M_AXI_GMEM_ACT_ID_WIDTH = 1;
    localparam C_M_AXI_GMEM_ACT_ADDR_WIDTH = 64;
    localparam C_M_AXI_GMEM_ACT_DATA_WIDTH = 128;
    localparam C_M_AXI_GMEM_ACT_AWUSER_WIDTH = 1;
    localparam C_M_AXI_GMEM_ACT_ARUSER_WIDTH = 1;
    localparam C_M_AXI_GMEM_ACT_WUSER_WIDTH = 1;
    localparam C_M_AXI_GMEM_ACT_RUSER_WIDTH = 1;
    localparam C_M_AXI_GMEM_ACT_BUSER_WIDTH = 1;
    localparam C_M_AXI_GMEM_ACT_USER_VALUE = 0;
    localparam C_M_AXI_GMEM_ACT_PROT_VALUE = 0;
    localparam C_M_AXI_GMEM_ACT_CACHE_VALUE = 3;
    localparam C_M_AXI_DATA_WIDTH = 32;
    localparam C_M_AXI_GMEM_OUT_ID_WIDTH = 1;
    localparam C_M_AXI_GMEM_OUT_ADDR_WIDTH = 64;
    localparam C_M_AXI_GMEM_OUT_DATA_WIDTH = 128;
    localparam C_M_AXI_GMEM_OUT_AWUSER_WIDTH = 1;
    localparam C_M_AXI_GMEM_OUT_ARUSER_WIDTH = 1;
    localparam C_M_AXI_GMEM_OUT_WUSER_WIDTH = 1;
    localparam C_M_AXI_GMEM_OUT_RUSER_WIDTH = 1;
    localparam C_M_AXI_GMEM_OUT_BUSER_WIDTH = 1;
    localparam C_M_AXI_GMEM_OUT_USER_VALUE = 0;
    localparam C_M_AXI_GMEM_OUT_PROT_VALUE = 0;
    localparam C_M_AXI_GMEM_OUT_CACHE_VALUE = 3;
    localparam C_M_AXI_GMEM_W0_ID_WIDTH = 1;
    localparam C_M_AXI_GMEM_W0_ADDR_WIDTH = 64;
    localparam C_M_AXI_GMEM_W0_DATA_WIDTH = 128;
    localparam C_M_AXI_GMEM_W0_AWUSER_WIDTH = 1;
    localparam C_M_AXI_GMEM_W0_ARUSER_WIDTH = 1;
    localparam C_M_AXI_GMEM_W0_WUSER_WIDTH = 1;
    localparam C_M_AXI_GMEM_W0_RUSER_WIDTH = 1;
    localparam C_M_AXI_GMEM_W0_BUSER_WIDTH = 1;
    localparam C_M_AXI_GMEM_W0_USER_VALUE = 0;
    localparam C_M_AXI_GMEM_W0_PROT_VALUE = 0;
    localparam C_M_AXI_GMEM_W0_CACHE_VALUE = 3;
    localparam C_M_AXI_GMEM_W1_ID_WIDTH = 1;
    localparam C_M_AXI_GMEM_W1_ADDR_WIDTH = 64;
    localparam C_M_AXI_GMEM_W1_DATA_WIDTH = 128;
    localparam C_M_AXI_GMEM_W1_AWUSER_WIDTH = 1;
    localparam C_M_AXI_GMEM_W1_ARUSER_WIDTH = 1;
    localparam C_M_AXI_GMEM_W1_WUSER_WIDTH = 1;
    localparam C_M_AXI_GMEM_W1_RUSER_WIDTH = 1;
    localparam C_M_AXI_GMEM_W1_BUSER_WIDTH = 1;
    localparam C_M_AXI_GMEM_W1_USER_VALUE = 0;
    localparam C_M_AXI_GMEM_W1_PROT_VALUE = 0;
    localparam C_M_AXI_GMEM_W1_CACHE_VALUE = 3;
    localparam C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
    localparam C_S_AXI_WSTRB_WIDTH = (32 / 8);
    localparam C_M_AXI_GMEM_ACT_WSTRB_WIDTH = (128 / 8);
    localparam C_M_AXI_WSTRB_WIDTH = (32 / 8);
    localparam C_M_AXI_GMEM_OUT_WSTRB_WIDTH = (128 / 8);
    localparam C_M_AXI_GMEM_W0_WSTRB_WIDTH = (128 / 8);
    localparam C_M_AXI_GMEM_W1_WSTRB_WIDTH = (128 / 8);

    localparam int WATCHDOG_CYCLES = 300_000;
    localparam int MEM_BYTES = 4194304;
    localparam int AXI_BYTES = 16;
    localparam int SA_M = 32;
    localparam int SA_N = 32;
    localparam int TILE_K = 128;
    localparam int GROUP = 32;
    localparam int GROUPS_PER_KTILE = 4;
    localparam int OUT_FRAC = 20;
    localparam int DISABLED_EXP = -128;
    localparam int WEIGHT_COLS_PER_PORT = 16;
    localparam int WEIGHT_WORDS_PER_KTILE_PER_PORT = 128;
    localparam int SCALE_WORDS_PER_KTILE_PER_PORT = 8;

    logic ap_clk;
    logic ap_rst_n;
    logic m_axi_gmem_w0_AWVALID;
    logic m_axi_gmem_w0_AWREADY;
    logic [C_M_AXI_GMEM_W0_ADDR_WIDTH - 1:0] m_axi_gmem_w0_AWADDR;
    logic [C_M_AXI_GMEM_W0_ID_WIDTH - 1:0] m_axi_gmem_w0_AWID;
    logic [7:0] m_axi_gmem_w0_AWLEN;
    logic [2:0] m_axi_gmem_w0_AWSIZE;
    logic [1:0] m_axi_gmem_w0_AWBURST;
    logic [1:0] m_axi_gmem_w0_AWLOCK;
    logic [3:0] m_axi_gmem_w0_AWCACHE;
    logic [2:0] m_axi_gmem_w0_AWPROT;
    logic [3:0] m_axi_gmem_w0_AWQOS;
    logic [3:0] m_axi_gmem_w0_AWREGION;
    logic [C_M_AXI_GMEM_W0_AWUSER_WIDTH - 1:0] m_axi_gmem_w0_AWUSER;
    logic m_axi_gmem_w0_WVALID;
    logic m_axi_gmem_w0_WREADY;
    logic [C_M_AXI_GMEM_W0_DATA_WIDTH - 1:0] m_axi_gmem_w0_WDATA;
    logic [C_M_AXI_GMEM_W0_WSTRB_WIDTH - 1:0] m_axi_gmem_w0_WSTRB;
    logic m_axi_gmem_w0_WLAST;
    logic [C_M_AXI_GMEM_W0_ID_WIDTH - 1:0] m_axi_gmem_w0_WID;
    logic [C_M_AXI_GMEM_W0_WUSER_WIDTH - 1:0] m_axi_gmem_w0_WUSER;
    logic m_axi_gmem_w0_ARVALID;
    logic m_axi_gmem_w0_ARREADY;
    logic [C_M_AXI_GMEM_W0_ADDR_WIDTH - 1:0] m_axi_gmem_w0_ARADDR;
    logic [C_M_AXI_GMEM_W0_ID_WIDTH - 1:0] m_axi_gmem_w0_ARID;
    logic [7:0] m_axi_gmem_w0_ARLEN;
    logic [2:0] m_axi_gmem_w0_ARSIZE;
    logic [1:0] m_axi_gmem_w0_ARBURST;
    logic [1:0] m_axi_gmem_w0_ARLOCK;
    logic [3:0] m_axi_gmem_w0_ARCACHE;
    logic [2:0] m_axi_gmem_w0_ARPROT;
    logic [3:0] m_axi_gmem_w0_ARQOS;
    logic [3:0] m_axi_gmem_w0_ARREGION;
    logic [C_M_AXI_GMEM_W0_ARUSER_WIDTH - 1:0] m_axi_gmem_w0_ARUSER;
    logic m_axi_gmem_w0_RVALID;
    logic m_axi_gmem_w0_RREADY;
    logic [C_M_AXI_GMEM_W0_DATA_WIDTH - 1:0] m_axi_gmem_w0_RDATA;
    logic m_axi_gmem_w0_RLAST;
    logic [C_M_AXI_GMEM_W0_ID_WIDTH - 1:0] m_axi_gmem_w0_RID;
    logic [C_M_AXI_GMEM_W0_RUSER_WIDTH - 1:0] m_axi_gmem_w0_RUSER;
    logic [1:0] m_axi_gmem_w0_RRESP;
    logic m_axi_gmem_w0_BVALID;
    logic m_axi_gmem_w0_BREADY;
    logic [1:0] m_axi_gmem_w0_BRESP;
    logic [C_M_AXI_GMEM_W0_ID_WIDTH - 1:0] m_axi_gmem_w0_BID;
    logic [C_M_AXI_GMEM_W0_BUSER_WIDTH - 1:0] m_axi_gmem_w0_BUSER;
    logic m_axi_gmem_w1_AWVALID;
    logic m_axi_gmem_w1_AWREADY;
    logic [C_M_AXI_GMEM_W1_ADDR_WIDTH - 1:0] m_axi_gmem_w1_AWADDR;
    logic [C_M_AXI_GMEM_W1_ID_WIDTH - 1:0] m_axi_gmem_w1_AWID;
    logic [7:0] m_axi_gmem_w1_AWLEN;
    logic [2:0] m_axi_gmem_w1_AWSIZE;
    logic [1:0] m_axi_gmem_w1_AWBURST;
    logic [1:0] m_axi_gmem_w1_AWLOCK;
    logic [3:0] m_axi_gmem_w1_AWCACHE;
    logic [2:0] m_axi_gmem_w1_AWPROT;
    logic [3:0] m_axi_gmem_w1_AWQOS;
    logic [3:0] m_axi_gmem_w1_AWREGION;
    logic [C_M_AXI_GMEM_W1_AWUSER_WIDTH - 1:0] m_axi_gmem_w1_AWUSER;
    logic m_axi_gmem_w1_WVALID;
    logic m_axi_gmem_w1_WREADY;
    logic [C_M_AXI_GMEM_W1_DATA_WIDTH - 1:0] m_axi_gmem_w1_WDATA;
    logic [C_M_AXI_GMEM_W1_WSTRB_WIDTH - 1:0] m_axi_gmem_w1_WSTRB;
    logic m_axi_gmem_w1_WLAST;
    logic [C_M_AXI_GMEM_W1_ID_WIDTH - 1:0] m_axi_gmem_w1_WID;
    logic [C_M_AXI_GMEM_W1_WUSER_WIDTH - 1:0] m_axi_gmem_w1_WUSER;
    logic m_axi_gmem_w1_ARVALID;
    logic m_axi_gmem_w1_ARREADY;
    logic [C_M_AXI_GMEM_W1_ADDR_WIDTH - 1:0] m_axi_gmem_w1_ARADDR;
    logic [C_M_AXI_GMEM_W1_ID_WIDTH - 1:0] m_axi_gmem_w1_ARID;
    logic [7:0] m_axi_gmem_w1_ARLEN;
    logic [2:0] m_axi_gmem_w1_ARSIZE;
    logic [1:0] m_axi_gmem_w1_ARBURST;
    logic [1:0] m_axi_gmem_w1_ARLOCK;
    logic [3:0] m_axi_gmem_w1_ARCACHE;
    logic [2:0] m_axi_gmem_w1_ARPROT;
    logic [3:0] m_axi_gmem_w1_ARQOS;
    logic [3:0] m_axi_gmem_w1_ARREGION;
    logic [C_M_AXI_GMEM_W1_ARUSER_WIDTH - 1:0] m_axi_gmem_w1_ARUSER;
    logic m_axi_gmem_w1_RVALID;
    logic m_axi_gmem_w1_RREADY;
    logic [C_M_AXI_GMEM_W1_DATA_WIDTH - 1:0] m_axi_gmem_w1_RDATA;
    logic m_axi_gmem_w1_RLAST;
    logic [C_M_AXI_GMEM_W1_ID_WIDTH - 1:0] m_axi_gmem_w1_RID;
    logic [C_M_AXI_GMEM_W1_RUSER_WIDTH - 1:0] m_axi_gmem_w1_RUSER;
    logic [1:0] m_axi_gmem_w1_RRESP;
    logic m_axi_gmem_w1_BVALID;
    logic m_axi_gmem_w1_BREADY;
    logic [1:0] m_axi_gmem_w1_BRESP;
    logic [C_M_AXI_GMEM_W1_ID_WIDTH - 1:0] m_axi_gmem_w1_BID;
    logic [C_M_AXI_GMEM_W1_BUSER_WIDTH - 1:0] m_axi_gmem_w1_BUSER;
    logic m_axi_gmem_act_AWVALID;
    logic m_axi_gmem_act_AWREADY;
    logic [C_M_AXI_GMEM_ACT_ADDR_WIDTH - 1:0] m_axi_gmem_act_AWADDR;
    logic [C_M_AXI_GMEM_ACT_ID_WIDTH - 1:0] m_axi_gmem_act_AWID;
    logic [7:0] m_axi_gmem_act_AWLEN;
    logic [2:0] m_axi_gmem_act_AWSIZE;
    logic [1:0] m_axi_gmem_act_AWBURST;
    logic [1:0] m_axi_gmem_act_AWLOCK;
    logic [3:0] m_axi_gmem_act_AWCACHE;
    logic [2:0] m_axi_gmem_act_AWPROT;
    logic [3:0] m_axi_gmem_act_AWQOS;
    logic [3:0] m_axi_gmem_act_AWREGION;
    logic [C_M_AXI_GMEM_ACT_AWUSER_WIDTH - 1:0] m_axi_gmem_act_AWUSER;
    logic m_axi_gmem_act_WVALID;
    logic m_axi_gmem_act_WREADY;
    logic [C_M_AXI_GMEM_ACT_DATA_WIDTH - 1:0] m_axi_gmem_act_WDATA;
    logic [C_M_AXI_GMEM_ACT_WSTRB_WIDTH - 1:0] m_axi_gmem_act_WSTRB;
    logic m_axi_gmem_act_WLAST;
    logic [C_M_AXI_GMEM_ACT_ID_WIDTH - 1:0] m_axi_gmem_act_WID;
    logic [C_M_AXI_GMEM_ACT_WUSER_WIDTH - 1:0] m_axi_gmem_act_WUSER;
    logic m_axi_gmem_act_ARVALID;
    logic m_axi_gmem_act_ARREADY;
    logic [C_M_AXI_GMEM_ACT_ADDR_WIDTH - 1:0] m_axi_gmem_act_ARADDR;
    logic [C_M_AXI_GMEM_ACT_ID_WIDTH - 1:0] m_axi_gmem_act_ARID;
    logic [7:0] m_axi_gmem_act_ARLEN;
    logic [2:0] m_axi_gmem_act_ARSIZE;
    logic [1:0] m_axi_gmem_act_ARBURST;
    logic [1:0] m_axi_gmem_act_ARLOCK;
    logic [3:0] m_axi_gmem_act_ARCACHE;
    logic [2:0] m_axi_gmem_act_ARPROT;
    logic [3:0] m_axi_gmem_act_ARQOS;
    logic [3:0] m_axi_gmem_act_ARREGION;
    logic [C_M_AXI_GMEM_ACT_ARUSER_WIDTH - 1:0] m_axi_gmem_act_ARUSER;
    logic m_axi_gmem_act_RVALID;
    logic m_axi_gmem_act_RREADY;
    logic [C_M_AXI_GMEM_ACT_DATA_WIDTH - 1:0] m_axi_gmem_act_RDATA;
    logic m_axi_gmem_act_RLAST;
    logic [C_M_AXI_GMEM_ACT_ID_WIDTH - 1:0] m_axi_gmem_act_RID;
    logic [C_M_AXI_GMEM_ACT_RUSER_WIDTH - 1:0] m_axi_gmem_act_RUSER;
    logic [1:0] m_axi_gmem_act_RRESP;
    logic m_axi_gmem_act_BVALID;
    logic m_axi_gmem_act_BREADY;
    logic [1:0] m_axi_gmem_act_BRESP;
    logic [C_M_AXI_GMEM_ACT_ID_WIDTH - 1:0] m_axi_gmem_act_BID;
    logic [C_M_AXI_GMEM_ACT_BUSER_WIDTH - 1:0] m_axi_gmem_act_BUSER;
    logic m_axi_gmem_out_AWVALID;
    logic m_axi_gmem_out_AWREADY;
    logic [C_M_AXI_GMEM_OUT_ADDR_WIDTH - 1:0] m_axi_gmem_out_AWADDR;
    logic [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_AWID;
    logic [7:0] m_axi_gmem_out_AWLEN;
    logic [2:0] m_axi_gmem_out_AWSIZE;
    logic [1:0] m_axi_gmem_out_AWBURST;
    logic [1:0] m_axi_gmem_out_AWLOCK;
    logic [3:0] m_axi_gmem_out_AWCACHE;
    logic [2:0] m_axi_gmem_out_AWPROT;
    logic [3:0] m_axi_gmem_out_AWQOS;
    logic [3:0] m_axi_gmem_out_AWREGION;
    logic [C_M_AXI_GMEM_OUT_AWUSER_WIDTH - 1:0] m_axi_gmem_out_AWUSER;
    logic m_axi_gmem_out_WVALID;
    logic m_axi_gmem_out_WREADY;
    logic [C_M_AXI_GMEM_OUT_DATA_WIDTH - 1:0] m_axi_gmem_out_WDATA;
    logic [C_M_AXI_GMEM_OUT_WSTRB_WIDTH - 1:0] m_axi_gmem_out_WSTRB;
    logic m_axi_gmem_out_WLAST;
    logic [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_WID;
    logic [C_M_AXI_GMEM_OUT_WUSER_WIDTH - 1:0] m_axi_gmem_out_WUSER;
    logic m_axi_gmem_out_ARVALID;
    logic m_axi_gmem_out_ARREADY;
    logic [C_M_AXI_GMEM_OUT_ADDR_WIDTH - 1:0] m_axi_gmem_out_ARADDR;
    logic [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_ARID;
    logic [7:0] m_axi_gmem_out_ARLEN;
    logic [2:0] m_axi_gmem_out_ARSIZE;
    logic [1:0] m_axi_gmem_out_ARBURST;
    logic [1:0] m_axi_gmem_out_ARLOCK;
    logic [3:0] m_axi_gmem_out_ARCACHE;
    logic [2:0] m_axi_gmem_out_ARPROT;
    logic [3:0] m_axi_gmem_out_ARQOS;
    logic [3:0] m_axi_gmem_out_ARREGION;
    logic [C_M_AXI_GMEM_OUT_ARUSER_WIDTH - 1:0] m_axi_gmem_out_ARUSER;
    logic m_axi_gmem_out_RVALID;
    logic m_axi_gmem_out_RREADY;
    logic [C_M_AXI_GMEM_OUT_DATA_WIDTH - 1:0] m_axi_gmem_out_RDATA;
    logic m_axi_gmem_out_RLAST;
    logic [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_RID;
    logic [C_M_AXI_GMEM_OUT_RUSER_WIDTH - 1:0] m_axi_gmem_out_RUSER;
    logic [1:0] m_axi_gmem_out_RRESP;
    logic m_axi_gmem_out_BVALID;
    logic m_axi_gmem_out_BREADY;
    logic [1:0] m_axi_gmem_out_BRESP;
    logic [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_BID;
    logic [C_M_AXI_GMEM_OUT_BUSER_WIDTH - 1:0] m_axi_gmem_out_BUSER;
    logic [255:0] m_axis_a_stream_TDATA;
    logic m_axis_a_stream_TVALID;
    logic m_axis_a_stream_TREADY;
    logic [255:0] m_axis_w_stream_TDATA;
    logic m_axis_w_stream_TVALID;
    logic m_axis_w_stream_TREADY;
    logic [15:0] m_axis_ctrl_stream_TDATA;
    logic m_axis_ctrl_stream_TVALID;
    logic m_axis_ctrl_stream_TREADY;
    logic [255:0] s_axis_psum_stream_TDATA;
    logic s_axis_psum_stream_TVALID;
    logic s_axis_psum_stream_TREADY;
    logic s_axi_control_AWVALID;
    logic s_axi_control_AWREADY;
    logic [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
    logic s_axi_control_WVALID;
    logic s_axi_control_WREADY;
    logic [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
    logic [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
    logic s_axi_control_ARVALID;
    logic s_axi_control_ARREADY;
    logic [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
    logic s_axi_control_RVALID;
    logic s_axi_control_RREADY;
    logic [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
    logic [1:0] s_axi_control_RRESP;
    logic s_axi_control_BVALID;
    logic s_axi_control_BREADY;
    logic [1:0] s_axi_control_BRESP;
    logic interrupt;

    logic pe_psum_tlast_unused;
    logic [7:0] mem_w0  [0:MEM_BYTES-1];
    logic [7:0] mem_w1  [0:MEM_BYTES-1];
    logic [7:0] mem_act [0:MEM_BYTES-1];
    logic [7:0] mem_out [0:MEM_BYTES-1];
    integer ffn_ref_mid_q [0:31][0:3071];
    integer ffn_ref_mid_e [0:31][0:95];

    initial ap_clk = 1'b0;
    always #5 ap_clk = ~ap_clk;

    vlm_engine_v4 dut (
        .ap_clk(ap_clk),
        .ap_rst_n(ap_rst_n),
        .m_axi_gmem_w0_AWVALID(m_axi_gmem_w0_AWVALID),
        .m_axi_gmem_w0_AWREADY(m_axi_gmem_w0_AWREADY),
        .m_axi_gmem_w0_AWADDR(m_axi_gmem_w0_AWADDR),
        .m_axi_gmem_w0_AWID(m_axi_gmem_w0_AWID),
        .m_axi_gmem_w0_AWLEN(m_axi_gmem_w0_AWLEN),
        .m_axi_gmem_w0_AWSIZE(m_axi_gmem_w0_AWSIZE),
        .m_axi_gmem_w0_AWBURST(m_axi_gmem_w0_AWBURST),
        .m_axi_gmem_w0_AWLOCK(m_axi_gmem_w0_AWLOCK),
        .m_axi_gmem_w0_AWCACHE(m_axi_gmem_w0_AWCACHE),
        .m_axi_gmem_w0_AWPROT(m_axi_gmem_w0_AWPROT),
        .m_axi_gmem_w0_AWQOS(m_axi_gmem_w0_AWQOS),
        .m_axi_gmem_w0_AWREGION(m_axi_gmem_w0_AWREGION),
        .m_axi_gmem_w0_AWUSER(m_axi_gmem_w0_AWUSER),
        .m_axi_gmem_w0_WVALID(m_axi_gmem_w0_WVALID),
        .m_axi_gmem_w0_WREADY(m_axi_gmem_w0_WREADY),
        .m_axi_gmem_w0_WDATA(m_axi_gmem_w0_WDATA),
        .m_axi_gmem_w0_WSTRB(m_axi_gmem_w0_WSTRB),
        .m_axi_gmem_w0_WLAST(m_axi_gmem_w0_WLAST),
        .m_axi_gmem_w0_WID(m_axi_gmem_w0_WID),
        .m_axi_gmem_w0_WUSER(m_axi_gmem_w0_WUSER),
        .m_axi_gmem_w0_ARVALID(m_axi_gmem_w0_ARVALID),
        .m_axi_gmem_w0_ARREADY(m_axi_gmem_w0_ARREADY),
        .m_axi_gmem_w0_ARADDR(m_axi_gmem_w0_ARADDR),
        .m_axi_gmem_w0_ARID(m_axi_gmem_w0_ARID),
        .m_axi_gmem_w0_ARLEN(m_axi_gmem_w0_ARLEN),
        .m_axi_gmem_w0_ARSIZE(m_axi_gmem_w0_ARSIZE),
        .m_axi_gmem_w0_ARBURST(m_axi_gmem_w0_ARBURST),
        .m_axi_gmem_w0_ARLOCK(m_axi_gmem_w0_ARLOCK),
        .m_axi_gmem_w0_ARCACHE(m_axi_gmem_w0_ARCACHE),
        .m_axi_gmem_w0_ARPROT(m_axi_gmem_w0_ARPROT),
        .m_axi_gmem_w0_ARQOS(m_axi_gmem_w0_ARQOS),
        .m_axi_gmem_w0_ARREGION(m_axi_gmem_w0_ARREGION),
        .m_axi_gmem_w0_ARUSER(m_axi_gmem_w0_ARUSER),
        .m_axi_gmem_w0_RVALID(m_axi_gmem_w0_RVALID),
        .m_axi_gmem_w0_RREADY(m_axi_gmem_w0_RREADY),
        .m_axi_gmem_w0_RDATA(m_axi_gmem_w0_RDATA),
        .m_axi_gmem_w0_RLAST(m_axi_gmem_w0_RLAST),
        .m_axi_gmem_w0_RID(m_axi_gmem_w0_RID),
        .m_axi_gmem_w0_RUSER(m_axi_gmem_w0_RUSER),
        .m_axi_gmem_w0_RRESP(m_axi_gmem_w0_RRESP),
        .m_axi_gmem_w0_BVALID(m_axi_gmem_w0_BVALID),
        .m_axi_gmem_w0_BREADY(m_axi_gmem_w0_BREADY),
        .m_axi_gmem_w0_BRESP(m_axi_gmem_w0_BRESP),
        .m_axi_gmem_w0_BID(m_axi_gmem_w0_BID),
        .m_axi_gmem_w0_BUSER(m_axi_gmem_w0_BUSER),
        .m_axi_gmem_w1_AWVALID(m_axi_gmem_w1_AWVALID),
        .m_axi_gmem_w1_AWREADY(m_axi_gmem_w1_AWREADY),
        .m_axi_gmem_w1_AWADDR(m_axi_gmem_w1_AWADDR),
        .m_axi_gmem_w1_AWID(m_axi_gmem_w1_AWID),
        .m_axi_gmem_w1_AWLEN(m_axi_gmem_w1_AWLEN),
        .m_axi_gmem_w1_AWSIZE(m_axi_gmem_w1_AWSIZE),
        .m_axi_gmem_w1_AWBURST(m_axi_gmem_w1_AWBURST),
        .m_axi_gmem_w1_AWLOCK(m_axi_gmem_w1_AWLOCK),
        .m_axi_gmem_w1_AWCACHE(m_axi_gmem_w1_AWCACHE),
        .m_axi_gmem_w1_AWPROT(m_axi_gmem_w1_AWPROT),
        .m_axi_gmem_w1_AWQOS(m_axi_gmem_w1_AWQOS),
        .m_axi_gmem_w1_AWREGION(m_axi_gmem_w1_AWREGION),
        .m_axi_gmem_w1_AWUSER(m_axi_gmem_w1_AWUSER),
        .m_axi_gmem_w1_WVALID(m_axi_gmem_w1_WVALID),
        .m_axi_gmem_w1_WREADY(m_axi_gmem_w1_WREADY),
        .m_axi_gmem_w1_WDATA(m_axi_gmem_w1_WDATA),
        .m_axi_gmem_w1_WSTRB(m_axi_gmem_w1_WSTRB),
        .m_axi_gmem_w1_WLAST(m_axi_gmem_w1_WLAST),
        .m_axi_gmem_w1_WID(m_axi_gmem_w1_WID),
        .m_axi_gmem_w1_WUSER(m_axi_gmem_w1_WUSER),
        .m_axi_gmem_w1_ARVALID(m_axi_gmem_w1_ARVALID),
        .m_axi_gmem_w1_ARREADY(m_axi_gmem_w1_ARREADY),
        .m_axi_gmem_w1_ARADDR(m_axi_gmem_w1_ARADDR),
        .m_axi_gmem_w1_ARID(m_axi_gmem_w1_ARID),
        .m_axi_gmem_w1_ARLEN(m_axi_gmem_w1_ARLEN),
        .m_axi_gmem_w1_ARSIZE(m_axi_gmem_w1_ARSIZE),
        .m_axi_gmem_w1_ARBURST(m_axi_gmem_w1_ARBURST),
        .m_axi_gmem_w1_ARLOCK(m_axi_gmem_w1_ARLOCK),
        .m_axi_gmem_w1_ARCACHE(m_axi_gmem_w1_ARCACHE),
        .m_axi_gmem_w1_ARPROT(m_axi_gmem_w1_ARPROT),
        .m_axi_gmem_w1_ARQOS(m_axi_gmem_w1_ARQOS),
        .m_axi_gmem_w1_ARREGION(m_axi_gmem_w1_ARREGION),
        .m_axi_gmem_w1_ARUSER(m_axi_gmem_w1_ARUSER),
        .m_axi_gmem_w1_RVALID(m_axi_gmem_w1_RVALID),
        .m_axi_gmem_w1_RREADY(m_axi_gmem_w1_RREADY),
        .m_axi_gmem_w1_RDATA(m_axi_gmem_w1_RDATA),
        .m_axi_gmem_w1_RLAST(m_axi_gmem_w1_RLAST),
        .m_axi_gmem_w1_RID(m_axi_gmem_w1_RID),
        .m_axi_gmem_w1_RUSER(m_axi_gmem_w1_RUSER),
        .m_axi_gmem_w1_RRESP(m_axi_gmem_w1_RRESP),
        .m_axi_gmem_w1_BVALID(m_axi_gmem_w1_BVALID),
        .m_axi_gmem_w1_BREADY(m_axi_gmem_w1_BREADY),
        .m_axi_gmem_w1_BRESP(m_axi_gmem_w1_BRESP),
        .m_axi_gmem_w1_BID(m_axi_gmem_w1_BID),
        .m_axi_gmem_w1_BUSER(m_axi_gmem_w1_BUSER),
        .m_axi_gmem_act_AWVALID(m_axi_gmem_act_AWVALID),
        .m_axi_gmem_act_AWREADY(m_axi_gmem_act_AWREADY),
        .m_axi_gmem_act_AWADDR(m_axi_gmem_act_AWADDR),
        .m_axi_gmem_act_AWID(m_axi_gmem_act_AWID),
        .m_axi_gmem_act_AWLEN(m_axi_gmem_act_AWLEN),
        .m_axi_gmem_act_AWSIZE(m_axi_gmem_act_AWSIZE),
        .m_axi_gmem_act_AWBURST(m_axi_gmem_act_AWBURST),
        .m_axi_gmem_act_AWLOCK(m_axi_gmem_act_AWLOCK),
        .m_axi_gmem_act_AWCACHE(m_axi_gmem_act_AWCACHE),
        .m_axi_gmem_act_AWPROT(m_axi_gmem_act_AWPROT),
        .m_axi_gmem_act_AWQOS(m_axi_gmem_act_AWQOS),
        .m_axi_gmem_act_AWREGION(m_axi_gmem_act_AWREGION),
        .m_axi_gmem_act_AWUSER(m_axi_gmem_act_AWUSER),
        .m_axi_gmem_act_WVALID(m_axi_gmem_act_WVALID),
        .m_axi_gmem_act_WREADY(m_axi_gmem_act_WREADY),
        .m_axi_gmem_act_WDATA(m_axi_gmem_act_WDATA),
        .m_axi_gmem_act_WSTRB(m_axi_gmem_act_WSTRB),
        .m_axi_gmem_act_WLAST(m_axi_gmem_act_WLAST),
        .m_axi_gmem_act_WID(m_axi_gmem_act_WID),
        .m_axi_gmem_act_WUSER(m_axi_gmem_act_WUSER),
        .m_axi_gmem_act_ARVALID(m_axi_gmem_act_ARVALID),
        .m_axi_gmem_act_ARREADY(m_axi_gmem_act_ARREADY),
        .m_axi_gmem_act_ARADDR(m_axi_gmem_act_ARADDR),
        .m_axi_gmem_act_ARID(m_axi_gmem_act_ARID),
        .m_axi_gmem_act_ARLEN(m_axi_gmem_act_ARLEN),
        .m_axi_gmem_act_ARSIZE(m_axi_gmem_act_ARSIZE),
        .m_axi_gmem_act_ARBURST(m_axi_gmem_act_ARBURST),
        .m_axi_gmem_act_ARLOCK(m_axi_gmem_act_ARLOCK),
        .m_axi_gmem_act_ARCACHE(m_axi_gmem_act_ARCACHE),
        .m_axi_gmem_act_ARPROT(m_axi_gmem_act_ARPROT),
        .m_axi_gmem_act_ARQOS(m_axi_gmem_act_ARQOS),
        .m_axi_gmem_act_ARREGION(m_axi_gmem_act_ARREGION),
        .m_axi_gmem_act_ARUSER(m_axi_gmem_act_ARUSER),
        .m_axi_gmem_act_RVALID(m_axi_gmem_act_RVALID),
        .m_axi_gmem_act_RREADY(m_axi_gmem_act_RREADY),
        .m_axi_gmem_act_RDATA(m_axi_gmem_act_RDATA),
        .m_axi_gmem_act_RLAST(m_axi_gmem_act_RLAST),
        .m_axi_gmem_act_RID(m_axi_gmem_act_RID),
        .m_axi_gmem_act_RUSER(m_axi_gmem_act_RUSER),
        .m_axi_gmem_act_RRESP(m_axi_gmem_act_RRESP),
        .m_axi_gmem_act_BVALID(m_axi_gmem_act_BVALID),
        .m_axi_gmem_act_BREADY(m_axi_gmem_act_BREADY),
        .m_axi_gmem_act_BRESP(m_axi_gmem_act_BRESP),
        .m_axi_gmem_act_BID(m_axi_gmem_act_BID),
        .m_axi_gmem_act_BUSER(m_axi_gmem_act_BUSER),
        .m_axi_gmem_out_AWVALID(m_axi_gmem_out_AWVALID),
        .m_axi_gmem_out_AWREADY(m_axi_gmem_out_AWREADY),
        .m_axi_gmem_out_AWADDR(m_axi_gmem_out_AWADDR),
        .m_axi_gmem_out_AWID(m_axi_gmem_out_AWID),
        .m_axi_gmem_out_AWLEN(m_axi_gmem_out_AWLEN),
        .m_axi_gmem_out_AWSIZE(m_axi_gmem_out_AWSIZE),
        .m_axi_gmem_out_AWBURST(m_axi_gmem_out_AWBURST),
        .m_axi_gmem_out_AWLOCK(m_axi_gmem_out_AWLOCK),
        .m_axi_gmem_out_AWCACHE(m_axi_gmem_out_AWCACHE),
        .m_axi_gmem_out_AWPROT(m_axi_gmem_out_AWPROT),
        .m_axi_gmem_out_AWQOS(m_axi_gmem_out_AWQOS),
        .m_axi_gmem_out_AWREGION(m_axi_gmem_out_AWREGION),
        .m_axi_gmem_out_AWUSER(m_axi_gmem_out_AWUSER),
        .m_axi_gmem_out_WVALID(m_axi_gmem_out_WVALID),
        .m_axi_gmem_out_WREADY(m_axi_gmem_out_WREADY),
        .m_axi_gmem_out_WDATA(m_axi_gmem_out_WDATA),
        .m_axi_gmem_out_WSTRB(m_axi_gmem_out_WSTRB),
        .m_axi_gmem_out_WLAST(m_axi_gmem_out_WLAST),
        .m_axi_gmem_out_WID(m_axi_gmem_out_WID),
        .m_axi_gmem_out_WUSER(m_axi_gmem_out_WUSER),
        .m_axi_gmem_out_ARVALID(m_axi_gmem_out_ARVALID),
        .m_axi_gmem_out_ARREADY(m_axi_gmem_out_ARREADY),
        .m_axi_gmem_out_ARADDR(m_axi_gmem_out_ARADDR),
        .m_axi_gmem_out_ARID(m_axi_gmem_out_ARID),
        .m_axi_gmem_out_ARLEN(m_axi_gmem_out_ARLEN),
        .m_axi_gmem_out_ARSIZE(m_axi_gmem_out_ARSIZE),
        .m_axi_gmem_out_ARBURST(m_axi_gmem_out_ARBURST),
        .m_axi_gmem_out_ARLOCK(m_axi_gmem_out_ARLOCK),
        .m_axi_gmem_out_ARCACHE(m_axi_gmem_out_ARCACHE),
        .m_axi_gmem_out_ARPROT(m_axi_gmem_out_ARPROT),
        .m_axi_gmem_out_ARQOS(m_axi_gmem_out_ARQOS),
        .m_axi_gmem_out_ARREGION(m_axi_gmem_out_ARREGION),
        .m_axi_gmem_out_ARUSER(m_axi_gmem_out_ARUSER),
        .m_axi_gmem_out_RVALID(m_axi_gmem_out_RVALID),
        .m_axi_gmem_out_RREADY(m_axi_gmem_out_RREADY),
        .m_axi_gmem_out_RDATA(m_axi_gmem_out_RDATA),
        .m_axi_gmem_out_RLAST(m_axi_gmem_out_RLAST),
        .m_axi_gmem_out_RID(m_axi_gmem_out_RID),
        .m_axi_gmem_out_RUSER(m_axi_gmem_out_RUSER),
        .m_axi_gmem_out_RRESP(m_axi_gmem_out_RRESP),
        .m_axi_gmem_out_BVALID(m_axi_gmem_out_BVALID),
        .m_axi_gmem_out_BREADY(m_axi_gmem_out_BREADY),
        .m_axi_gmem_out_BRESP(m_axi_gmem_out_BRESP),
        .m_axi_gmem_out_BID(m_axi_gmem_out_BID),
        .m_axi_gmem_out_BUSER(m_axi_gmem_out_BUSER),
        .m_axis_a_stream_TDATA(m_axis_a_stream_TDATA),
        .m_axis_a_stream_TVALID(m_axis_a_stream_TVALID),
        .m_axis_a_stream_TREADY(m_axis_a_stream_TREADY),
        .m_axis_w_stream_TDATA(m_axis_w_stream_TDATA),
        .m_axis_w_stream_TVALID(m_axis_w_stream_TVALID),
        .m_axis_w_stream_TREADY(m_axis_w_stream_TREADY),
        .m_axis_ctrl_stream_TDATA(m_axis_ctrl_stream_TDATA),
        .m_axis_ctrl_stream_TVALID(m_axis_ctrl_stream_TVALID),
        .m_axis_ctrl_stream_TREADY(m_axis_ctrl_stream_TREADY),
        .s_axis_psum_stream_TDATA(s_axis_psum_stream_TDATA),
        .s_axis_psum_stream_TVALID(s_axis_psum_stream_TVALID),
        .s_axis_psum_stream_TREADY(s_axis_psum_stream_TREADY),
        .s_axi_control_AWVALID(s_axi_control_AWVALID),
        .s_axi_control_AWREADY(s_axi_control_AWREADY),
        .s_axi_control_AWADDR(s_axi_control_AWADDR),
        .s_axi_control_WVALID(s_axi_control_WVALID),
        .s_axi_control_WREADY(s_axi_control_WREADY),
        .s_axi_control_WDATA(s_axi_control_WDATA),
        .s_axi_control_WSTRB(s_axi_control_WSTRB),
        .s_axi_control_ARVALID(s_axi_control_ARVALID),
        .s_axi_control_ARREADY(s_axi_control_ARREADY),
        .s_axi_control_ARADDR(s_axi_control_ARADDR),
        .s_axi_control_RVALID(s_axi_control_RVALID),
        .s_axi_control_RREADY(s_axi_control_RREADY),
        .s_axi_control_RDATA(s_axi_control_RDATA),
        .s_axi_control_RRESP(s_axi_control_RRESP),
        .s_axi_control_BVALID(s_axi_control_BVALID),
        .s_axi_control_BREADY(s_axi_control_BREADY),
        .s_axi_control_BRESP(s_axi_control_BRESP),
        .interrupt(interrupt)
    );

    pe_array_axis pe_array (
        .ap_clk(ap_clk),
        .ap_rst_n(ap_rst_n),
        .s_axis_a_tdata(m_axis_a_stream_TDATA),
        .s_axis_a_tvalid(m_axis_a_stream_TVALID),
        .s_axis_a_tready(m_axis_a_stream_TREADY),
        .s_axis_w_tdata(m_axis_w_stream_TDATA),
        .s_axis_w_tvalid(m_axis_w_stream_TVALID),
        .s_axis_w_tready(m_axis_w_stream_TREADY),
        .s_axis_ctrl_tdata(m_axis_ctrl_stream_TDATA),
        .s_axis_ctrl_tvalid(m_axis_ctrl_stream_TVALID),
        .s_axis_ctrl_tready(m_axis_ctrl_stream_TREADY),
        .m_axis_psum_tdata(s_axis_psum_stream_TDATA),
        .m_axis_psum_tvalid(s_axis_psum_stream_TVALID),
        .m_axis_psum_tready(s_axis_psum_stream_TREADY),
        .m_axis_psum_tlast(pe_psum_tlast_unused)
    );

    function automatic [127:0] read_w0(input [63:0] addr);
        integer i;
        begin
            read_w0 = 128'd0;
            for (i = 0; i < AXI_BYTES; i = i + 1)
                if ((addr + i) < MEM_BYTES) read_w0[i*8 +: 8] = mem_w0[addr + i];
        end
    endfunction

    function automatic [127:0] read_w1(input [63:0] addr);
        integer i;
        begin
            read_w1 = 128'd0;
            for (i = 0; i < AXI_BYTES; i = i + 1)
                if ((addr + i) < MEM_BYTES) read_w1[i*8 +: 8] = mem_w1[addr + i];
        end
    endfunction

    function automatic [127:0] read_act(input [63:0] addr);
        integer i;
        begin
            read_act = 128'd0;
            for (i = 0; i < AXI_BYTES; i = i + 1)
                if ((addr + i) < MEM_BYTES) read_act[i*8 +: 8] = mem_act[addr + i];
        end
    endfunction

    function automatic [127:0] read_out(input [63:0] addr);
        integer i;
        begin
            read_out = 128'd0;
            for (i = 0; i < AXI_BYTES; i = i + 1)
                if ((addr + i) < MEM_BYTES) read_out[i*8 +: 8] = mem_out[addr + i];
        end
    endfunction

    function automatic void write_w0(input [63:0] addr, input [127:0] data, input [15:0] strb);
        integer i;
        begin
            for (i = 0; i < AXI_BYTES; i = i + 1)
                if (strb[i] && (addr + i) < MEM_BYTES) mem_w0[addr + i] = data[i*8 +: 8];
        end
    endfunction

    function automatic void write_w1(input [63:0] addr, input [127:0] data, input [15:0] strb);
        integer i;
        begin
            for (i = 0; i < AXI_BYTES; i = i + 1)
                if (strb[i] && (addr + i) < MEM_BYTES) mem_w1[addr + i] = data[i*8 +: 8];
        end
    endfunction

    function automatic void write_act(input [63:0] addr, input [127:0] data, input [15:0] strb);
        integer i;
        begin
            for (i = 0; i < AXI_BYTES; i = i + 1)
                if (strb[i] && (addr + i) < MEM_BYTES) mem_act[addr + i] = data[i*8 +: 8];
        end
    endfunction

    function automatic void write_out(input [63:0] addr, input [127:0] data, input [15:0] strb);
        integer i;
        begin
            for (i = 0; i < AXI_BYTES; i = i + 1)
                if (strb[i] && (addr + i) < MEM_BYTES) mem_out[addr + i] = data[i*8 +: 8];
        end
    endfunction


    // AXI memory responder for m_axi_gmem_w0. One outstanding read and one
    // outstanding write burst are enough for this closed-loop RTL gate.
    logic m_axi_gmem_w0_r_busy;
    logic [63:0] m_axi_gmem_w0_r_addr;
    logic [8:0]  m_axi_gmem_w0_r_left;
    logic m_axi_gmem_w0_w_busy;
    logic [63:0] m_axi_gmem_w0_w_addr;

    assign m_axi_gmem_w0_ARREADY = !m_axi_gmem_w0_r_busy && !m_axi_gmem_w0_RVALID;
    assign m_axi_gmem_w0_AWREADY = !m_axi_gmem_w0_w_busy && !m_axi_gmem_w0_BVALID;
    assign m_axi_gmem_w0_WREADY  = m_axi_gmem_w0_w_busy;

    always_ff @(posedge ap_clk) begin
        if (!ap_rst_n) begin
            m_axi_gmem_w0_r_busy <= 1'b0;
            m_axi_gmem_w0_r_addr <= 64'd0;
            m_axi_gmem_w0_r_left <= 9'd0;
            m_axi_gmem_w0_RVALID <= 1'b0;
            m_axi_gmem_w0_RDATA  <= 128'd0;
            m_axi_gmem_w0_RLAST  <= 1'b0;
            m_axi_gmem_w0_RID    <= 1'd0;
            m_axi_gmem_w0_RUSER  <= 1'd0;
            m_axi_gmem_w0_RRESP  <= 2'd0;
        end else begin
            if (m_axi_gmem_w0_RVALID && !m_axi_gmem_w0_RREADY) begin
                // Hold current read beat until accepted.
            end else if (m_axi_gmem_w0_r_busy) begin
                m_axi_gmem_w0_RVALID <= 1'b1;
                m_axi_gmem_w0_RDATA  <= read_w0(m_axi_gmem_w0_r_addr);
                m_axi_gmem_w0_RLAST  <= (m_axi_gmem_w0_r_left == 9'd1);
                m_axi_gmem_w0_RID    <= 1'd0;
                m_axi_gmem_w0_RUSER  <= 1'd0;
                m_axi_gmem_w0_RRESP  <= 2'd0;
                m_axi_gmem_w0_r_addr <= m_axi_gmem_w0_r_addr + 64'd16;
                if (m_axi_gmem_w0_r_left == 9'd1) begin
                    m_axi_gmem_w0_r_busy <= 1'b0;
                    m_axi_gmem_w0_r_left <= 9'd0;
                end else begin
                    m_axi_gmem_w0_r_left <= m_axi_gmem_w0_r_left - 9'd1;
                end
            end else if (m_axi_gmem_w0_ARVALID && m_axi_gmem_w0_ARREADY) begin
                m_axi_gmem_w0_r_busy <= 1'b1;
                m_axi_gmem_w0_r_addr <= m_axi_gmem_w0_ARADDR;
                m_axi_gmem_w0_r_left <= {1'b0, m_axi_gmem_w0_ARLEN} + 9'd1;
                m_axi_gmem_w0_RVALID <= 1'b0;
                m_axi_gmem_w0_RLAST  <= 1'b0;
            end else begin
                m_axi_gmem_w0_RVALID <= 1'b0;
                m_axi_gmem_w0_RLAST  <= 1'b0;
            end
        end
    end

    assign m_axi_gmem_w0_BRESP = 2'd0;
    assign m_axi_gmem_w0_BID   = 1'd0;
    assign m_axi_gmem_w0_BUSER = 1'd0;
    always_ff @(posedge ap_clk) begin
        if (!ap_rst_n) begin
            m_axi_gmem_w0_w_busy <= 1'b0;
            m_axi_gmem_w0_w_addr <= 64'd0;
            m_axi_gmem_w0_BVALID <= 1'b0;
        end else begin
            if (m_axi_gmem_w0_BVALID && m_axi_gmem_w0_BREADY) begin
                m_axi_gmem_w0_BVALID <= 1'b0;
            end
            if (m_axi_gmem_w0_AWVALID && m_axi_gmem_w0_AWREADY) begin
                m_axi_gmem_w0_w_busy <= 1'b1;
                m_axi_gmem_w0_w_addr <= m_axi_gmem_w0_AWADDR;
            end
            if (m_axi_gmem_w0_WVALID && m_axi_gmem_w0_WREADY) begin
                write_w0(m_axi_gmem_w0_w_addr, m_axi_gmem_w0_WDATA, m_axi_gmem_w0_WSTRB);
                m_axi_gmem_w0_w_addr <= m_axi_gmem_w0_w_addr + 64'd16;
                if (m_axi_gmem_w0_WLAST) begin
                    m_axi_gmem_w0_w_busy <= 1'b0;
                    m_axi_gmem_w0_BVALID <= 1'b1;
                end
            end
        end
    end


    // AXI memory responder for m_axi_gmem_w1. One outstanding read and one
    // outstanding write burst are enough for this closed-loop RTL gate.
    logic m_axi_gmem_w1_r_busy;
    logic [63:0] m_axi_gmem_w1_r_addr;
    logic [8:0]  m_axi_gmem_w1_r_left;
    logic m_axi_gmem_w1_w_busy;
    logic [63:0] m_axi_gmem_w1_w_addr;

    assign m_axi_gmem_w1_ARREADY = !m_axi_gmem_w1_r_busy && !m_axi_gmem_w1_RVALID;
    assign m_axi_gmem_w1_AWREADY = !m_axi_gmem_w1_w_busy && !m_axi_gmem_w1_BVALID;
    assign m_axi_gmem_w1_WREADY  = m_axi_gmem_w1_w_busy;

    always_ff @(posedge ap_clk) begin
        if (!ap_rst_n) begin
            m_axi_gmem_w1_r_busy <= 1'b0;
            m_axi_gmem_w1_r_addr <= 64'd0;
            m_axi_gmem_w1_r_left <= 9'd0;
            m_axi_gmem_w1_RVALID <= 1'b0;
            m_axi_gmem_w1_RDATA  <= 128'd0;
            m_axi_gmem_w1_RLAST  <= 1'b0;
            m_axi_gmem_w1_RID    <= 1'd0;
            m_axi_gmem_w1_RUSER  <= 1'd0;
            m_axi_gmem_w1_RRESP  <= 2'd0;
        end else begin
            if (m_axi_gmem_w1_RVALID && !m_axi_gmem_w1_RREADY) begin
                // Hold current read beat until accepted.
            end else if (m_axi_gmem_w1_r_busy) begin
                m_axi_gmem_w1_RVALID <= 1'b1;
                m_axi_gmem_w1_RDATA  <= read_w1(m_axi_gmem_w1_r_addr);
                m_axi_gmem_w1_RLAST  <= (m_axi_gmem_w1_r_left == 9'd1);
                m_axi_gmem_w1_RID    <= 1'd0;
                m_axi_gmem_w1_RUSER  <= 1'd0;
                m_axi_gmem_w1_RRESP  <= 2'd0;
                m_axi_gmem_w1_r_addr <= m_axi_gmem_w1_r_addr + 64'd16;
                if (m_axi_gmem_w1_r_left == 9'd1) begin
                    m_axi_gmem_w1_r_busy <= 1'b0;
                    m_axi_gmem_w1_r_left <= 9'd0;
                end else begin
                    m_axi_gmem_w1_r_left <= m_axi_gmem_w1_r_left - 9'd1;
                end
            end else if (m_axi_gmem_w1_ARVALID && m_axi_gmem_w1_ARREADY) begin
                m_axi_gmem_w1_r_busy <= 1'b1;
                m_axi_gmem_w1_r_addr <= m_axi_gmem_w1_ARADDR;
                m_axi_gmem_w1_r_left <= {1'b0, m_axi_gmem_w1_ARLEN} + 9'd1;
                m_axi_gmem_w1_RVALID <= 1'b0;
                m_axi_gmem_w1_RLAST  <= 1'b0;
            end else begin
                m_axi_gmem_w1_RVALID <= 1'b0;
                m_axi_gmem_w1_RLAST  <= 1'b0;
            end
        end
    end

    assign m_axi_gmem_w1_BRESP = 2'd0;
    assign m_axi_gmem_w1_BID   = 1'd0;
    assign m_axi_gmem_w1_BUSER = 1'd0;
    always_ff @(posedge ap_clk) begin
        if (!ap_rst_n) begin
            m_axi_gmem_w1_w_busy <= 1'b0;
            m_axi_gmem_w1_w_addr <= 64'd0;
            m_axi_gmem_w1_BVALID <= 1'b0;
        end else begin
            if (m_axi_gmem_w1_BVALID && m_axi_gmem_w1_BREADY) begin
                m_axi_gmem_w1_BVALID <= 1'b0;
            end
            if (m_axi_gmem_w1_AWVALID && m_axi_gmem_w1_AWREADY) begin
                m_axi_gmem_w1_w_busy <= 1'b1;
                m_axi_gmem_w1_w_addr <= m_axi_gmem_w1_AWADDR;
            end
            if (m_axi_gmem_w1_WVALID && m_axi_gmem_w1_WREADY) begin
                write_w1(m_axi_gmem_w1_w_addr, m_axi_gmem_w1_WDATA, m_axi_gmem_w1_WSTRB);
                m_axi_gmem_w1_w_addr <= m_axi_gmem_w1_w_addr + 64'd16;
                if (m_axi_gmem_w1_WLAST) begin
                    m_axi_gmem_w1_w_busy <= 1'b0;
                    m_axi_gmem_w1_BVALID <= 1'b1;
                end
            end
        end
    end


    // AXI memory responder for m_axi_gmem_act. One outstanding read and one
    // outstanding write burst are enough for this closed-loop RTL gate.
    logic m_axi_gmem_act_r_busy;
    logic [63:0] m_axi_gmem_act_r_addr;
    logic [8:0]  m_axi_gmem_act_r_left;
    logic m_axi_gmem_act_w_busy;
    logic [63:0] m_axi_gmem_act_w_addr;

    assign m_axi_gmem_act_ARREADY = !m_axi_gmem_act_r_busy && !m_axi_gmem_act_RVALID;
    assign m_axi_gmem_act_AWREADY = !m_axi_gmem_act_w_busy && !m_axi_gmem_act_BVALID;
    assign m_axi_gmem_act_WREADY  = m_axi_gmem_act_w_busy;

    always_ff @(posedge ap_clk) begin
        if (!ap_rst_n) begin
            m_axi_gmem_act_r_busy <= 1'b0;
            m_axi_gmem_act_r_addr <= 64'd0;
            m_axi_gmem_act_r_left <= 9'd0;
            m_axi_gmem_act_RVALID <= 1'b0;
            m_axi_gmem_act_RDATA  <= 128'd0;
            m_axi_gmem_act_RLAST  <= 1'b0;
            m_axi_gmem_act_RID    <= 1'd0;
            m_axi_gmem_act_RUSER  <= 1'd0;
            m_axi_gmem_act_RRESP  <= 2'd0;
        end else begin
            if (m_axi_gmem_act_RVALID && !m_axi_gmem_act_RREADY) begin
                // Hold current read beat until accepted.
            end else if (m_axi_gmem_act_r_busy) begin
                m_axi_gmem_act_RVALID <= 1'b1;
                m_axi_gmem_act_RDATA  <= read_act(m_axi_gmem_act_r_addr);
                m_axi_gmem_act_RLAST  <= (m_axi_gmem_act_r_left == 9'd1);
                m_axi_gmem_act_RID    <= 1'd0;
                m_axi_gmem_act_RUSER  <= 1'd0;
                m_axi_gmem_act_RRESP  <= 2'd0;
                m_axi_gmem_act_r_addr <= m_axi_gmem_act_r_addr + 64'd16;
                if (m_axi_gmem_act_r_left == 9'd1) begin
                    m_axi_gmem_act_r_busy <= 1'b0;
                    m_axi_gmem_act_r_left <= 9'd0;
                end else begin
                    m_axi_gmem_act_r_left <= m_axi_gmem_act_r_left - 9'd1;
                end
            end else if (m_axi_gmem_act_ARVALID && m_axi_gmem_act_ARREADY) begin
                m_axi_gmem_act_r_busy <= 1'b1;
                m_axi_gmem_act_r_addr <= m_axi_gmem_act_ARADDR;
                m_axi_gmem_act_r_left <= {1'b0, m_axi_gmem_act_ARLEN} + 9'd1;
                m_axi_gmem_act_RVALID <= 1'b0;
                m_axi_gmem_act_RLAST  <= 1'b0;
            end else begin
                m_axi_gmem_act_RVALID <= 1'b0;
                m_axi_gmem_act_RLAST  <= 1'b0;
            end
        end
    end

    assign m_axi_gmem_act_BRESP = 2'd0;
    assign m_axi_gmem_act_BID   = 1'd0;
    assign m_axi_gmem_act_BUSER = 1'd0;
    always_ff @(posedge ap_clk) begin
        if (!ap_rst_n) begin
            m_axi_gmem_act_w_busy <= 1'b0;
            m_axi_gmem_act_w_addr <= 64'd0;
            m_axi_gmem_act_BVALID <= 1'b0;
        end else begin
            if (m_axi_gmem_act_BVALID && m_axi_gmem_act_BREADY) begin
                m_axi_gmem_act_BVALID <= 1'b0;
            end
            if (m_axi_gmem_act_AWVALID && m_axi_gmem_act_AWREADY) begin
                m_axi_gmem_act_w_busy <= 1'b1;
                m_axi_gmem_act_w_addr <= m_axi_gmem_act_AWADDR;
            end
            if (m_axi_gmem_act_WVALID && m_axi_gmem_act_WREADY) begin
                write_act(m_axi_gmem_act_w_addr, m_axi_gmem_act_WDATA, m_axi_gmem_act_WSTRB);
                m_axi_gmem_act_w_addr <= m_axi_gmem_act_w_addr + 64'd16;
                if (m_axi_gmem_act_WLAST) begin
                    m_axi_gmem_act_w_busy <= 1'b0;
                    m_axi_gmem_act_BVALID <= 1'b1;
                end
            end
        end
    end


    // AXI memory responder for m_axi_gmem_out. One outstanding read and one
    // outstanding write burst are enough for this closed-loop RTL gate.
    logic m_axi_gmem_out_r_busy;
    logic [63:0] m_axi_gmem_out_r_addr;
    logic [8:0]  m_axi_gmem_out_r_left;
    logic m_axi_gmem_out_w_busy;
    logic [63:0] m_axi_gmem_out_w_addr;

    assign m_axi_gmem_out_ARREADY = !m_axi_gmem_out_r_busy && !m_axi_gmem_out_RVALID;
    assign m_axi_gmem_out_AWREADY = !m_axi_gmem_out_w_busy && !m_axi_gmem_out_BVALID;
    assign m_axi_gmem_out_WREADY  = m_axi_gmem_out_w_busy;

    always_ff @(posedge ap_clk) begin
        if (!ap_rst_n) begin
            m_axi_gmem_out_r_busy <= 1'b0;
            m_axi_gmem_out_r_addr <= 64'd0;
            m_axi_gmem_out_r_left <= 9'd0;
            m_axi_gmem_out_RVALID <= 1'b0;
            m_axi_gmem_out_RDATA  <= 128'd0;
            m_axi_gmem_out_RLAST  <= 1'b0;
            m_axi_gmem_out_RID    <= 1'd0;
            m_axi_gmem_out_RUSER  <= 1'd0;
            m_axi_gmem_out_RRESP  <= 2'd0;
        end else begin
            if (m_axi_gmem_out_RVALID && !m_axi_gmem_out_RREADY) begin
                // Hold current read beat until accepted.
            end else if (m_axi_gmem_out_r_busy) begin
                m_axi_gmem_out_RVALID <= 1'b1;
                m_axi_gmem_out_RDATA  <= read_out(m_axi_gmem_out_r_addr);
                m_axi_gmem_out_RLAST  <= (m_axi_gmem_out_r_left == 9'd1);
                m_axi_gmem_out_RID    <= 1'd0;
                m_axi_gmem_out_RUSER  <= 1'd0;
                m_axi_gmem_out_RRESP  <= 2'd0;
                m_axi_gmem_out_r_addr <= m_axi_gmem_out_r_addr + 64'd16;
                if (m_axi_gmem_out_r_left == 9'd1) begin
                    m_axi_gmem_out_r_busy <= 1'b0;
                    m_axi_gmem_out_r_left <= 9'd0;
                end else begin
                    m_axi_gmem_out_r_left <= m_axi_gmem_out_r_left - 9'd1;
                end
            end else if (m_axi_gmem_out_ARVALID && m_axi_gmem_out_ARREADY) begin
                m_axi_gmem_out_r_busy <= 1'b1;
                m_axi_gmem_out_r_addr <= m_axi_gmem_out_ARADDR;
                m_axi_gmem_out_r_left <= {1'b0, m_axi_gmem_out_ARLEN} + 9'd1;
                m_axi_gmem_out_RVALID <= 1'b0;
                m_axi_gmem_out_RLAST  <= 1'b0;
            end else begin
                m_axi_gmem_out_RVALID <= 1'b0;
                m_axi_gmem_out_RLAST  <= 1'b0;
            end
        end
    end

    assign m_axi_gmem_out_BRESP = 2'd0;
    assign m_axi_gmem_out_BID   = 1'd0;
    assign m_axi_gmem_out_BUSER = 1'd0;
    always_ff @(posedge ap_clk) begin
        if (!ap_rst_n) begin
            m_axi_gmem_out_w_busy <= 1'b0;
            m_axi_gmem_out_w_addr <= 64'd0;
            m_axi_gmem_out_BVALID <= 1'b0;
        end else begin
            if (m_axi_gmem_out_BVALID && m_axi_gmem_out_BREADY) begin
                m_axi_gmem_out_BVALID <= 1'b0;
            end
            if (m_axi_gmem_out_AWVALID && m_axi_gmem_out_AWREADY) begin
                m_axi_gmem_out_w_busy <= 1'b1;
                m_axi_gmem_out_w_addr <= m_axi_gmem_out_AWADDR;
            end
            if (m_axi_gmem_out_WVALID && m_axi_gmem_out_WREADY) begin
                write_out(m_axi_gmem_out_w_addr, m_axi_gmem_out_WDATA, m_axi_gmem_out_WSTRB);
                m_axi_gmem_out_w_addr <= m_axi_gmem_out_w_addr + 64'd16;
                if (m_axi_gmem_out_WLAST) begin
                    m_axi_gmem_out_w_busy <= 1'b0;
                    m_axi_gmem_out_BVALID <= 1'b1;
                end
            end
        end
    end


    function automatic integer align_up(input integer value, input integer align);
        begin
            align_up = ((value + align - 1) / align) * align;
        end
    endfunction

    function automatic integer div_ceil(input integer value, input integer divisor);
        begin
            div_ceil = (value + divisor - 1) / divisor;
        end
    endfunction

    function automatic integer act_value(input integer m, input integer k);
        begin
            act_value = ((m * 5 + k * 3) % 13) - 6;
        end
    endfunction

    function automatic integer act_exp_value(input integer m, input integer g, input bit varied);
        begin
            act_exp_value = varied ? (((m + g * 3) % 3) - 1) : 0;
        end
    endfunction

    function automatic integer weight_value(input integer seed, input integer k, input integer n);
        begin
            weight_value = ((seed + k * 7 + n * 5) % 11) - 5;
        end
    endfunction

    function automatic integer sat_i64(input longint signed v);
        begin
            if (v > 2147483647) sat_i64 = 2147483647;
            else if (v < (-2147483647 - 1)) sat_i64 = (-2147483647 - 1);
            else sat_i64 = $signed(v[31:0]);
        end
    endfunction

    function automatic integer sat_i128(input logic signed [127:0] v);
        begin
            if (v > 128'sd2147483647) sat_i128 = 2147483647;
            else if (v < -(128'sd2147483648)) sat_i128 = (-2147483647 - 1);
            else sat_i128 = $signed(v[31:0]);
        end
    endfunction

    function automatic integer sat_add_i32(input integer a, input integer b);
        longint signed wide;
        begin
            wide = a;
            wide = wide + b;
            sat_add_i32 = sat_i64(wide);
        end
    endfunction

    function automatic integer shift_apply(input integer x, input integer e);
        integer shift;
        integer rs;
        longint signed wide;
        longint signed half;
        begin
            shift = e + OUT_FRAC;
            wide = x;
            if (shift >= 0) begin
                if (shift >= 31) begin
                    if (x > 0) shift_apply = 2147483647;
                    else if (x < 0) shift_apply = (-2147483647 - 1);
                    else shift_apply = 0;
                end else begin
                    wide = wide <<< shift;
                    shift_apply = sat_i64(wide);
                end
            end else begin
                rs = -shift;
                if (rs >= 63) begin
                    wide = 0;
                end else begin
                    half = 64'sd1 <<< (rs - 1);
                    wide = (wide >= 0) ? (wide + half) : (wide - half);
                    wide = wide >>> rs;
                end
                shift_apply = sat_i64(wide);
            end
        end
    endfunction

    function automatic integer hard_silu(input integer x);
        integer xp;
        integer cl;
        logic signed [127:0] p;
        begin
            xp = x + (3 <<< OUT_FRAC);
            cl = (xp < 0) ? 0 : ((xp > (6 <<< OUT_FRAC)) ? (6 <<< OUT_FRAC) : xp);
            p = x;
            p = p * cl;
            hard_silu = sat_i128((p * 128'sd2796203) >>> 44);
        end
    endfunction

    function automatic integer hard_gelu(input integer x);
        integer xp;
        integer cl;
        logic signed [127:0] p;
        begin
            xp = x + (3 <<< (OUT_FRAC - 1));
            cl = (xp < 0) ? 0 : ((xp > (3 <<< OUT_FRAC)) ? (3 <<< OUT_FRAC) : xp);
            p = x;
            p = p * cl;
            hard_gelu = sat_i128((p * 128'sd5592405) >>> 44);
        end
    endfunction

    function automatic integer round_mul_q20(input integer a, input integer b);
        longint signed p;
        longint signed half;
        begin
            p = a;
            p = p * b;
            half = 64'sd1 <<< (OUT_FRAC - 1);
            p = (p >= 0) ? (p + half) : (p - half);
            round_mul_q20 = sat_i64(p >>> OUT_FRAC);
        end
    endfunction

    function automatic integer choose_pot_exp_q20(input integer max_abs);
        integer selected_shift;
        integer shift;
        bit found;
        bit fits;
        longint signed scaled;
        begin
            if (max_abs <= 0) begin
                choose_pot_exp_q20 = 0;
            end else begin
                selected_shift = OUT_FRAC;
                found = 1'b0;
                for (shift = -10; shift <= 50; shift = shift + 1) begin
                    if (shift >= 0) begin
                        fits = (shift >= 31) || (max_abs <= (64'sd127 <<< shift));
                    end else begin
                        scaled = max_abs;
                        scaled = scaled <<< (-shift);
                        fits = (scaled <= 127);
                    end
                    if (fits && !found) begin
                        selected_shift = shift;
                        found = 1'b1;
                    end
                end
                choose_pot_exp_q20 = selected_shift - OUT_FRAC;
                if (choose_pot_exp_q20 < -30) choose_pot_exp_q20 = -30;
                if (choose_pot_exp_q20 > 30) choose_pot_exp_q20 = 30;
            end
        end
    endfunction

    function automatic integer quantize_q20_exp(input integer x, input integer exp);
        integer shift;
        integer q;
        longint signed wide;
        integer half;
        begin
            shift = exp + OUT_FRAC;
            if (shift >= 0) begin
                if (shift >= 31) q = 0;
                else if (shift == 0) q = x;
                else begin
                    half = 1 <<< (shift - 1);
                    q = (x >= 0) ? ((x + half) >>> shift) : ((x - half) >>> shift);
                end
            end else begin
                wide = x;
                wide = wide <<< (-shift);
                q = sat_i64(wide);
            end
            if (q > 127) q = 127;
            if (q < -127) q = -127;
            quantize_q20_exp = q;
        end
    endfunction

    function automatic integer r_i32_out(input integer addr);
        logic [31:0] v;
        begin
            v = {mem_out[addr + 3], mem_out[addr + 2], mem_out[addr + 1], mem_out[addr + 0]};
            r_i32_out = $signed(v);
        end
    endfunction

    task automatic clear_memories;
        integer i;
        begin
            for (i = 0; i < MEM_BYTES; i = i + 1) begin
                mem_w0[i] = 8'd0;
                mem_w1[i] = 8'd0;
                mem_act[i] = 8'd0;
                mem_out[i] = 8'd0;
            end
        end
    endtask

    task automatic wb_act(input integer off, input integer value);
        begin
            if (off >= 0 && off < MEM_BYTES) mem_act[off] = value[7:0];
        end
    endtask

    task automatic wb_weight(input integer port, input integer off, input integer value);
        begin
            if (off >= 0 && off < MEM_BYTES) begin
                if (port == 0) mem_w0[off] = value[7:0];
                else           mem_w1[off] = value[7:0];
            end
        end
    endtask

    task automatic wr32(input integer off, input [31:0] value);
        begin
            wb_act(off + 0, value[7:0]);
            wb_act(off + 1, value[15:8]);
            wb_act(off + 2, value[23:16]);
            wb_act(off + 3, value[31:24]);
        end
    endtask

    task automatic wr64(input integer off, input [63:0] value);
        begin
            wr32(off, value[31:0]);
            wr32(off + 4, value[63:32]);
        end
    endtask

    task automatic fill_act(input integer q_off, input integer s_off,
                            input integer rows, input integer K,
                            input integer row_stride, input integer scale_stride,
                            input bit varied_exp);
        integer m;
        integer k;
        integer g;
        integer groups;
        begin
            groups = K / GROUP;
            for (m = 0; m < rows; m = m + 1) begin
                for (k = 0; k < K; k = k + 1)
                    wb_act(q_off + m * row_stride + k, act_value(m, k));
                for (g = 0; g < groups; g = g + 1)
                    wb_act(s_off + m * scale_stride + g, act_exp_value(m, g, varied_exp));
            end
        end
    endtask

    task automatic pack_weight_ports_exp(input integer q0_off, input integer q1_off,
                                         input integer s0_off, input integer s1_off,
                                         input integer seed, input integer K, input integer N,
                                         input integer nt_stride_q, input integer nt_stride_s,
                                         input integer e0);
        integer k_tiles;
        integer n_tiles;
        integer nt;
        integer kt;
        integer lane;
        integer kw;
        integer b;
        integer word_off_bytes;
        integer k_in_tile;
        integer k_abs;
        integer n0;
        integer n1;
        integer q0_kt;
        integer q1_kt;
        integer s0_kt;
        integer s1_kt;
        integer byte_off;
        begin
            k_tiles = div_ceil(K, TILE_K);
            n_tiles = div_ceil(N, SA_N);
            for (nt = 0; nt < n_tiles; nt = nt + 1) begin
                for (kt = 0; kt < k_tiles; kt = kt + 1) begin
                    q0_kt = q0_off + nt * nt_stride_q + kt * WEIGHT_WORDS_PER_KTILE_PER_PORT * AXI_BYTES;
                    q1_kt = q1_off + nt * nt_stride_q + kt * WEIGHT_WORDS_PER_KTILE_PER_PORT * AXI_BYTES;
                    s0_kt = s0_off + nt * nt_stride_s + kt * SCALE_WORDS_PER_KTILE_PER_PORT * AXI_BYTES;
                    s1_kt = s1_off + nt * nt_stride_s + kt * SCALE_WORDS_PER_KTILE_PER_PORT * AXI_BYTES;
                    for (lane = 0; lane < WEIGHT_COLS_PER_PORT; lane = lane + 1) begin
                        for (kw = 0; kw < TILE_K / AXI_BYTES; kw = kw + 1) begin
                            word_off_bytes = (lane * (TILE_K / AXI_BYTES) + kw) * AXI_BYTES;
                            for (b = 0; b < AXI_BYTES; b = b + 1) begin
                                k_in_tile = kw * AXI_BYTES + b;
                                k_abs = kt * TILE_K + k_in_tile;
                                n0 = nt * SA_N + lane;
                                n1 = nt * SA_N + WEIGHT_COLS_PER_PORT + lane;
                                wb_weight(0, q0_kt + word_off_bytes + b,
                                          (k_abs < K && n0 < N) ? weight_value(seed, k_abs, n0) : 0);
                                wb_weight(1, q1_kt + word_off_bytes + b,
                                          (k_abs < K && n1 < N) ? weight_value(seed, k_abs, n1) : 0);
                            end
                        end
                        for (b = 0; b < GROUPS_PER_KTILE; b = b + 1) begin
                            byte_off = (lane * GROUPS_PER_KTILE + b) * 2;
                            wb_weight(0, s0_kt + byte_off + 0, e0);
                            wb_weight(0, s0_kt + byte_off + 1, DISABLED_EXP);
                            wb_weight(1, s1_kt + byte_off + 0, e0);
                            wb_weight(1, s1_kt + byte_off + 1, DISABLED_EXP);
                        end
                    end
                end
            end
        end
    endtask

    task automatic pack_weight_ports(input integer q0_off, input integer q1_off,
                                     input integer s0_off, input integer s1_off,
                                     input integer seed, input integer K, input integer N,
                                     input integer nt_stride_q, input integer nt_stride_s);
        begin
            pack_weight_ports_exp(q0_off, q1_off, s0_off, s1_off,
                                  seed, K, N, nt_stride_q, nt_stride_s, 0);
        end
    endtask

    task automatic init_dense_task(input integer K, input integer N,
                                   input integer act_q, input integer act_s,
                                   input integer act_row_stride,
                                   input integer act_scale_stride,
                                   input integer w_q0, input integer w_q1,
                                   input integer w_s0, input integer w_s1,
                                   input integer dst,
                                   input integer out_stride,
                                   input integer nt_q_stride,
                                   input integer nt_s_stride);
        begin
            wr32(0,  32'h384d4c56);
            wr32(4,  32'd11);
            wr32(8,  32'd64);
            wr32(12, 32'd32);
            wr64(16, act_q);
            wr64(24, act_s);
            wr32(32, act_row_stride);
            wr32(36, 32'd1);
            wr32(40, K);
            wr32(44, 32'd0);
            wr64(48, 64'd0);
            wr32(56, N); wr32(60, 32'd0); wr32(64, 32'd0);
            wr32(68, 32'd0);
            wr64(72, w_q0); wr64(80, w_q1);
            wr64(120, w_s0); wr64(128, w_s1);
            wr64(168, dst);
            wr32(192, out_stride);
            wr32(204, nt_q_stride);
            wr32(208, nt_s_stride);
            wr32(212, act_scale_stride);
        end
    endtask

    task automatic init_qkv_tail_task(input integer rows, input integer K,
                                      input integer act_q, input integer act_s,
                                      input integer act_row_stride,
                                      input integer act_scale_stride,
                                      input integer q0_0, input integer q1_0,
                                      input integer s0_0, input integer s1_0,
                                      input integer q0_1, input integer q1_1,
                                      input integer s0_1, input integer s1_1,
                                      input integer q0_2, input integer q1_2,
                                      input integer s0_2, input integer s1_2,
                                      input integer dst0, input integer dst1,
                                      input integer dst2,
                                      input integer out_stride,
                                      input integer nt_q_stride,
                                      input integer nt_s_stride);
        begin
            wr32(0,  32'h384d4c56);
            wr32(4,  32'd11);
            wr32(8,  32'd65);
            wr32(12, rows);
            wr64(16, act_q);
            wr64(24, act_s);
            wr32(32, act_row_stride);
            wr32(36, 32'd3);
            wr32(40, K);
            wr32(44, 32'd0);
            wr64(48, 64'd0);
            wr32(56, 32'd32); wr32(60, 32'd32); wr32(64, 32'd32);
            wr32(68, 32'd0);
            wr64(72, q0_0); wr64(80, q1_0);
            wr64(88, q0_1); wr64(96, q1_1);
            wr64(104, q0_2); wr64(112, q1_2);
            wr64(120, s0_0); wr64(128, s1_0);
            wr64(136, s0_1); wr64(144, s1_1);
            wr64(152, s0_2); wr64(160, s1_2);
            wr64(168, dst0); wr64(176, dst1); wr64(184, dst2);
            wr32(192, out_stride); wr32(196, out_stride); wr32(200, out_stride);
            wr32(204, nt_q_stride);
            wr32(208, nt_s_stride);
            wr32(212, act_scale_stride);
        end
    endtask

    task automatic init_ffn_task(input integer task_type, input integer activation,
                                 input integer K_in, input integer K_mid,
                                 input integer N_out,
                                 input integer act_q, input integer act_s,
                                 input integer act_row_stride,
                                 input integer act_scale_stride,
                                 input integer g_q0, input integer g_q1,
                                 input integer g_s0, input integer g_s1,
                                 input integer u_q0, input integer u_q1,
                                 input integer u_s0, input integer u_s1,
                                 input integer d_q0, input integer d_q1,
                                 input integer d_s0, input integer d_s1,
                                 input integer dst,
                                 input integer out_stride,
                                 input integer nt_q_stride_in,
                                 input integer nt_s_stride_in);
        begin
            wr32(0,  32'h384d4c56);
            wr32(4,  32'd11);
            wr32(8,  task_type);
            wr32(12, 32'd32);
            wr64(16, act_q);
            wr64(24, act_s);
            wr32(32, act_row_stride);
            wr32(36, 32'd1);
            wr32(40, K_in);
            wr32(44, activation);
            wr64(48, 64'd0);
            wr32(56, N_out); wr32(60, 32'd0); wr32(64, 32'd0);
            wr32(68, 32'd0);
            wr32(192, out_stride);
            wr32(204, nt_q_stride_in);
            wr32(208, nt_s_stride_in);
            wr32(212, act_scale_stride);
            wr64(216, g_q0); wr64(224, g_q1);
            wr64(232, g_s0); wr64(240, g_s1);
            wr64(248, u_q0); wr64(256, u_q1);
            wr64(264, u_s0); wr64(272, u_s1);
            wr64(280, d_q0); wr64(288, d_q1);
            wr64(296, d_s0); wr64(304, d_s1);
            wr64(312, dst);
            wr32(320, K_in);
            wr32(324, K_mid);
            wr32(328, N_out);
        end
    endtask

    task automatic init_liveness_task(input [31:0] task_type);
        integer output_count;
        begin
            clear_memories();
            output_count = (task_type == 32'd65) ? 3 : 1;

            wr32(0,  32'h384d4c56);
            wr32(4,  32'd11);
            wr32(8,  task_type);
            wr32(12, 32'd32);
            wr64(16, 64'd4096);
            wr64(24, 64'd8192);
            wr32(32, 32'd128);
            wr32(36, output_count);
            wr32(40, 32'd128);
            wr32(44, (task_type == 32'd67) ? 32'd1 : 32'd0);
            wr64(48, 64'd0);
            wr32(56, 32'd32); wr32(60, 32'd32); wr32(64, 32'd32);
            wr32(68, 32'd0);
            wr32(192, 32'd128); wr32(196, 32'd128); wr32(200, 32'd128);
            wr32(204, 32'd2048);
            wr32(208, 32'd128);
            wr32(212, 32'd16);
            wr32(320, 32'd128);
            wr32(324, 32'd128);
            wr32(328, 32'd32);
        end
    endtask

    task automatic ctrl_write(input [6:0] addr, input [31:0] data);
        bit aw_done;
        bit w_done;
        begin
            aw_done = 1'b0;
            w_done = 1'b0;
            @(negedge ap_clk);
            s_axi_control_AWADDR  = addr;
            s_axi_control_AWVALID = 1'b1;
            s_axi_control_WDATA   = data;
            s_axi_control_WSTRB   = 4'hf;
            s_axi_control_WVALID  = 1'b1;
            s_axi_control_BREADY  = 1'b1;
            while (!(aw_done && w_done)) begin
                @(posedge ap_clk);
                if (s_axi_control_AWREADY) begin
                    aw_done = 1'b1;
                    s_axi_control_AWVALID = 1'b0;
                end
                if (s_axi_control_WREADY) begin
                    w_done = 1'b1;
                    s_axi_control_WVALID = 1'b0;
                end
            end
            while (!s_axi_control_BVALID) @(posedge ap_clk);
            @(negedge ap_clk);
            s_axi_control_BREADY  = 1'b0;
        end
    endtask

    task automatic ctrl_read(input [6:0] addr, output [31:0] data);
        begin
            @(negedge ap_clk);
            s_axi_control_ARADDR  = addr;
            s_axi_control_ARVALID = 1'b1;
            s_axi_control_RREADY  = 1'b1;
            while (!s_axi_control_ARREADY) @(posedge ap_clk);
            @(negedge ap_clk);
            s_axi_control_ARVALID = 1'b0;
            while (!s_axi_control_RVALID) @(posedge ap_clk);
            data = s_axi_control_RDATA;
            @(negedge ap_clk);
            s_axi_control_RREADY  = 1'b0;
        end
    endtask

    task automatic reset_dut;
        begin
            ap_rst_n = 1'b0;
            s_axi_control_AWVALID = 1'b0;
            s_axi_control_AWADDR  = '0;
            s_axi_control_WVALID  = 1'b0;
            s_axi_control_WDATA   = '0;
            s_axi_control_WSTRB   = 4'h0;
            s_axi_control_BREADY  = 1'b0;
            s_axi_control_ARVALID = 1'b0;
            s_axi_control_ARADDR  = '0;
            s_axi_control_RREADY  = 1'b0;
            repeat (20) @(posedge ap_clk);
            ap_rst_n = 1'b1;
            repeat (10) @(posedge ap_clk);
        end
    endtask

    task automatic program_and_start;
        begin
            ctrl_write(7'h10, 32'd0);
            ctrl_write(7'h14, 32'd0);
            ctrl_write(7'h1c, 32'd0);
            ctrl_write(7'h20, 32'd0);
            ctrl_write(7'h28, 32'd0);
            ctrl_write(7'h2c, 32'd0);
            ctrl_write(7'h34, 32'd0);
            ctrl_write(7'h38, 32'd0);
            ctrl_write(7'h40, 32'd0);
            ctrl_write(7'h44, 32'd0);
            ctrl_write(7'h00, 32'd1);
        end
    endtask

    task automatic wait_done(input string name);
        integer cycle;
        reg [31:0] ap_ctrl;
        begin
            for (cycle = 0; cycle < WATCHDOG_CYCLES; cycle = cycle + 1) begin
                ctrl_read(7'h00, ap_ctrl);
                if (ap_ctrl[1]) begin
                    $display("[SYS] DONE %s cycles=%0d AP_CTRL=0x%08x", name, cycle, ap_ctrl);
                    return;
                end
                if ((cycle != 0) && ((cycle % 100000) == 0)) begin
                    $display("[SYS] WAIT %s cycles=%0d AP_CTRL=0x%08x AXI act_ar=%0b/%0b act_r=%0b/%0b w0_ar=%0b/%0b w0_r=%0b/%0b w1_ar=%0b/%0b w1_r=%0b/%0b out_aw=%0b/%0b out_w=%0b/%0b out_b=%0b/%0b AXIS a=%0b/%0b w=%0b/%0b c=%0b/%0b psum=%0b/%0b PE pending=%0b drain=%0b row=%0d half=%0d",
                             name, cycle, ap_ctrl,
                             m_axi_gmem_act_ARVALID, m_axi_gmem_act_ARREADY,
                             m_axi_gmem_act_RVALID,  m_axi_gmem_act_RREADY,
                             m_axi_gmem_w0_ARVALID,  m_axi_gmem_w0_ARREADY,
                             m_axi_gmem_w0_RVALID,   m_axi_gmem_w0_RREADY,
                             m_axi_gmem_w1_ARVALID,  m_axi_gmem_w1_ARREADY,
                             m_axi_gmem_w1_RVALID,   m_axi_gmem_w1_RREADY,
                             m_axi_gmem_out_AWVALID, m_axi_gmem_out_AWREADY,
                             m_axi_gmem_out_WVALID,  m_axi_gmem_out_WREADY,
                             m_axi_gmem_out_BVALID,  m_axi_gmem_out_BREADY,
                             m_axis_a_stream_TVALID,    m_axis_a_stream_TREADY,
                             m_axis_w_stream_TVALID,    m_axis_w_stream_TREADY,
                             m_axis_ctrl_stream_TVALID, m_axis_ctrl_stream_TREADY,
                             s_axis_psum_stream_TVALID, s_axis_psum_stream_TREADY,
                             pe_array.pending_valid, pe_array.drain_phase_active,
                             pe_array.drain_row_idx, pe_array.drain_half_idx);
                end
                repeat (8) @(posedge ap_clk);
            end
            $fatal(1, "[SYS] TIMEOUT %s last_AP_CTRL=0x%08x", name, ap_ctrl);
        end
    endtask

    task automatic run_liveness_case(input [31:0] task_type, input string name);
        begin
            $display("[SYS] START liveness %s task_type=%0d", name, task_type);
            reset_dut();
            init_liveness_task(task_type);
            program_and_start();
            wait_done(name);
        end
    endtask

    task automatic compare_dense_k768(input string name);
        integer m;
        integer n;
        integer kt;
        integer k;
        integer part;
        integer total;
        integer hw;
        integer expected;
        integer err;
        begin
            err = 0;
            for (m = 0; m < 32; m = m + 1) begin
                for (n = 0; n < 32; n = n + 1) begin
                    total = 0;
                    for (kt = 0; kt < div_ceil(768, GROUP); kt = kt + 1) begin
                        part = 0;
                        for (k = kt * GROUP; k < (kt + 1) * GROUP; k = k + 1)
                            part = part + act_value(m, k) * weight_value(165, k, n);
                        total = sat_add_i32(total, shift_apply(part, act_exp_value(m, kt, 1'b1)));
                    end
                    hw = r_i32_out(m * 128 + n * 4);
                    expected = total;
                    if (hw != expected) begin
                        if (err < 8) $display("[SYS] %s mismatch row=%0d col=%0d hw=%0d expected=%0d", name, m, n, hw, expected);
                        err = err + 1;
                    end
                end
            end
            if (err != 0) $fatal(1, "[SYS] FAIL %s mismatches=%0d", name, err);
            $display("[SYS] PASS %s numeric", name);
        end
    endtask

    task automatic run_numeric_dense_k768;
        integer K;
        integer N;
        integer kt;
        integer nt_q_stride;
        integer nt_s_stride;
        begin
            K = 768;
            N = 32;
            kt = 6;
            nt_q_stride = WEIGHT_WORDS_PER_KTILE_PER_PORT * AXI_BYTES * kt;
            nt_s_stride = SCALE_WORDS_PER_KTILE_PER_PORT * AXI_BYTES * kt;
            $display("[SYS] START numeric REAL_VISION_DENSE_K768");
            reset_dut();
            clear_memories();
            fill_act(4096, 65536, 32, K, 768, 32, 1'b1);
            pack_weight_ports(0, 0, nt_q_stride, nt_q_stride, 165, K, N, nt_q_stride, nt_s_stride);
            init_dense_task(K, N, 4096, 65536, 768, 32,
                            0, 0, nt_q_stride, nt_q_stride,
                            0, 128, nt_q_stride, nt_s_stride);
            program_and_start();
            wait_done("REAL_VISION_DENSE_K768");
            compare_dense_k768("REAL_VISION_DENSE_K768");
        end
    endtask

    task automatic compare_qkv_tail(input string name);
        integer rows;
        integer out_stride;
        integer dst_base [0:2];
        integer seed [0:2];
        integer o;
        integer m;
        integer n;
        integer k;
        integer kt;
        integer total;
        integer hw;
        integer err;
        begin
            rows = 46;
            out_stride = 128;
            dst_base[0] = 0;
            dst_base[1] = rows * out_stride;
            dst_base[2] = rows * out_stride * 2;
            seed[0] = 201;
            seed[1] = 224;
            seed[2] = 247;
            err = 0;
            for (o = 0; o < 3; o = o + 1) begin
                for (m = 0; m < rows; m = m + 1) begin
                    for (n = 0; n < 32; n = n + 1) begin
                        total = 0;
                        for (kt = 0; kt < div_ceil(128, GROUP); kt = kt + 1) begin
                            integer part;
                            part = 0;
                            for (k = kt * GROUP; k < (kt + 1) * GROUP; k = k + 1) begin
                                part = part + act_value(m, k) * weight_value(seed[o], k, n);
                            end
                            total = sat_add_i32(total, shift_apply(part, 0));
                        end
                        hw = r_i32_out(dst_base[o] + m * out_stride + n * 4);
                        if (hw != total) begin
                            if (err < 8) $display("[SYS] %s mismatch out=%0d row=%0d col=%0d hw=%0d ref=%0d", name, o, m, n, hw, total);
                            err = err + 1;
                        end
                    end
                end
            end
            if (err != 0) $fatal(1, "[SYS] FAIL %s mismatches=%0d", name, err);
            $display("[SYS] PASS %s numeric", name);
        end
    endtask

    task automatic run_numeric_qkv_tail_m46;
        integer rows;
        integer K;
        integer out_stride;
        integer nt_q_stride;
        integer nt_s_stride;
        integer q0_0;
        integer q0_1;
        integer q0_2;
        integer s0_0;
        integer s0_1;
        integer s0_2;
        integer dst0;
        integer dst1;
        integer dst2;
        begin
            rows = 46;
            K = 128;
            out_stride = 128;
            nt_q_stride = WEIGHT_WORDS_PER_KTILE_PER_PORT * AXI_BYTES;
            nt_s_stride = SCALE_WORDS_PER_KTILE_PER_PORT * AXI_BYTES;
            q0_0 = 0;
            q0_1 = 4096;
            q0_2 = 8192;
            s0_0 = 16384;
            s0_1 = 16640;
            s0_2 = 16896;
            dst0 = 0;
            dst1 = rows * out_stride;
            dst2 = rows * out_stride * 2;

            $display("[SYS] START numeric QKV_TAIL_M46_NO_OVERWRITE");
            reset_dut();
            clear_memories();
            fill_act(32768, 65536, rows, K, 128, 16, 1'b0);
            pack_weight_ports(q0_0, q0_0, s0_0, s0_0, 201, K, 32, nt_q_stride, nt_s_stride);
            pack_weight_ports(q0_1, q0_1, s0_1, s0_1, 224, K, 32, nt_q_stride, nt_s_stride);
            pack_weight_ports(q0_2, q0_2, s0_2, s0_2, 247, K, 32, nt_q_stride, nt_s_stride);
            init_qkv_tail_task(rows, K,
                               32768, 65536, 128, 16,
                               q0_0, q0_0, s0_0, s0_0,
                               q0_1, q0_1, s0_1, s0_1,
                               q0_2, q0_2, s0_2, s0_2,
                               dst0, dst1, dst2,
                               out_stride, nt_q_stride, nt_s_stride);
            program_and_start();
            wait_done("QKV_TAIL_M46_NO_OVERWRITE");
            compare_qkv_tail("QKV_TAIL_M46_NO_OVERWRITE");
        end
    endtask

    task automatic compare_ffn_stride(input string name);
        integer mid_q [0:31][0:255];
        integer mid_e [0:31][0:7];
        integer fused [0:31];
        integer m;
        integer mt;
        integer c;
        integer k;
        integer n;
        integer mc;
        integer gate;
        integer up;
        integer av;
        integer max_abs;
        integer q_exp;
        integer qv;
        integer abs_v;
        integer part;
        integer total;
        integer hw;
        integer err;
        longint signed prod;
        begin
            for (m = 0; m < 32; m = m + 1) begin
                for (mt = 0; mt < 8; mt = mt + 1) begin
                    for (c = 0; c < 32; c = c + 1) begin
                        mc = mt * 32 + c;
                        gate = 0;
                        up = 0;
                        for (k = 0; k < 128; k = k + 1) begin
                            gate = gate + act_value(m, k) * weight_value(97, k, mc);
                            up = up + act_value(m, k) * weight_value(113, k, mc);
                        end
                        gate = shift_apply(gate, 0);
                        up = shift_apply(up, 0);
                        av = hard_silu(gate);
                        fused[c] = round_mul_q20(av, up);
                    end
                    max_abs = 0;
                    for (c = 0; c < 32; c = c + 1) begin
                        abs_v = (fused[c] < 0) ? -fused[c] : fused[c];
                        if (abs_v > max_abs) max_abs = abs_v;
                    end
                    q_exp = choose_pot_exp_q20(max_abs);
                    mid_e[m][mt] = q_exp;
                    for (c = 0; c < 32; c = c + 1) begin
                        mid_q[m][mt * 32 + c] = quantize_q20_exp(fused[c], q_exp);
                    end
                end
            end

            err = 0;
            for (m = 0; m < 32; m = m + 1) begin
                for (n = 0; n < 64; n = n + 1) begin
                    total = 0;
                    for (mt = 0; mt < 8; mt = mt + 1) begin
                        part = 0;
                        for (c = 0; c < 32; c = c + 1) begin
                            mc = mt * 32 + c;
                            part = part + mid_q[m][mc] * weight_value(139, mc, n);
                        end
                        total = sat_add_i32(total, shift_apply(part, mid_e[m][mt]));
                    end
                    hw = r_i32_out(m * 256 + n * 4);
                    if (hw != total) begin
                        if (err < 8) $display("[SYS] %s mismatch row=%0d col=%0d hw=%0d ref=%0d", name, m, n, hw, total);
                        err = err + 1;
                    end
                end
            end
            if (err != 0) $fatal(1, "[SYS] FAIL %s mismatches=%0d", name, err);
            $display("[SYS] PASS %s numeric", name);
        end
    endtask

    task automatic compare_ffn_generic(input string name,
                                       input integer K_in,
                                       input integer K_mid,
                                       input integer N_out,
                                       input integer gate_seed,
                                       input integer up_seed,
                                       input integer down_seed,
                                       input integer activation,
                                       input integer out_stride,
                                       input bit varied_exp,
                                       input integer gateup_w_exp,
                                       input integer down_w_exp);
        integer m;
        integer mt;
        integer c;
        integer k;
        integer kt;
        integer n;
        integer mc;
        integer gate;
        integer gate_part;
        integer up;
        integer up_part;
        integer av;
        integer max_abs;
        integer q_exp;
        integer qv;
        integer abs_v;
        integer part;
        integer total;
        integer hw;
        integer err;
        integer groups_mid;
        longint signed prod;
        begin
            groups_mid = div_ceil(K_mid, TILE_K);
            for (m = 0; m < 32; m = m + 1) begin
                for (mt = 0; mt < groups_mid; mt = mt + 1) begin
                    for (c = 0; c < TILE_K; c = c + 1) begin
                        mc = mt * TILE_K + c;
                        if (mc < K_mid) begin
                            gate = 0;
                            up = 0;
                            for (kt = 0; kt < div_ceil(K_in, TILE_K); kt = kt + 1) begin
                                gate_part = 0;
                                up_part = 0;
                                for (k = kt * TILE_K; k < (kt + 1) * TILE_K; k = k + 1) begin
                                    if (k < K_in) begin
                                        gate_part = gate_part + act_value(m, k) * weight_value(gate_seed, k, mc);
                                        up_part = up_part + act_value(m, k) * weight_value(up_seed, k, mc);
                                    end
                                end
                                gate = sat_add_i32(gate, shift_apply(gate_part, act_exp_value(m, kt * GROUPS_PER_KTILE, varied_exp) + gateup_w_exp));
                                up = sat_add_i32(up, shift_apply(up_part, act_exp_value(m, kt * GROUPS_PER_KTILE, varied_exp) + gateup_w_exp));
                            end
                            av = (activation == 1) ? hard_gelu(gate) : hard_silu(gate);
                            ffn_ref_mid_q[m][mc] = round_mul_q20(av, up);
                        end else begin
                            ffn_ref_mid_q[m][mc] = 0;
                        end
                    end
                    max_abs = 0;
                    for (c = 0; c < TILE_K; c = c + 1) begin
                        mc = mt * TILE_K + c;
                        abs_v = (ffn_ref_mid_q[m][mc] < 0) ? -ffn_ref_mid_q[m][mc] : ffn_ref_mid_q[m][mc];
                        if (abs_v > max_abs) max_abs = abs_v;
                    end
                    q_exp = choose_pot_exp_q20(max_abs);
                    ffn_ref_mid_e[m][mt] = q_exp;
                    for (c = 0; c < TILE_K; c = c + 1) begin
                        mc = mt * TILE_K + c;
                        ffn_ref_mid_q[m][mc] = quantize_q20_exp(ffn_ref_mid_q[m][mc], q_exp);
                    end
                end
            end

            err = 0;
            for (m = 0; m < 32; m = m + 1) begin
                for (n = 0; n < N_out; n = n + 1) begin
                    total = 0;
                    for (mt = 0; mt < groups_mid; mt = mt + 1) begin
                        part = 0;
                        for (c = 0; c < TILE_K; c = c + 1) begin
                            mc = mt * TILE_K + c;
                            if (mc < K_mid) begin
                                part = part + ffn_ref_mid_q[m][mc] * weight_value(down_seed, mc, n);
                            end
                        end
                        total = sat_add_i32(total, shift_apply(part, ffn_ref_mid_e[m][mt] + down_w_exp));
                    end
                    hw = r_i32_out(m * out_stride + n * 4);
                    if (hw != total) begin
                        if (err < 8) $display("[SYS] %s mismatch row=%0d col=%0d hw=%0d ref=%0d", name, m, n, hw, total);
                        err = err + 1;
                    end
                end
            end
            if (err != 0) $fatal(1, "[SYS] FAIL %s mismatches=%0d", name, err);
            $display("[SYS] PASS %s numeric", name);
        end
    endtask

    task automatic run_numeric_ffn_stride;
        integer nt_q_stride_in;
        integer nt_s_stride_in;
        integer nt_q_stride_down;
        integer nt_s_stride_down;
        integer g_q;
        integer g_s;
        integer u_q;
        integer u_s;
        integer d_q;
        integer d_s;
        begin
            nt_q_stride_in = WEIGHT_WORDS_PER_KTILE_PER_PORT * AXI_BYTES;
            nt_s_stride_in = SCALE_WORDS_PER_KTILE_PER_PORT * AXI_BYTES;
            nt_q_stride_down = WEIGHT_WORDS_PER_KTILE_PER_PORT * AXI_BYTES * 2;
            nt_s_stride_down = SCALE_WORDS_PER_KTILE_PER_PORT * AXI_BYTES * 2;
            g_q = 0;
            g_s = 8 * nt_q_stride_in;
            u_q = g_s + 8 * nt_s_stride_in;
            u_s = u_q + 8 * nt_q_stride_in;
            d_q = u_s + 8 * nt_s_stride_in;
            d_s = d_q + 2 * nt_q_stride_down;

            $display("[SYS] START numeric FFN_DOWN_STRIDE_KMID256_KOUT64");
            reset_dut();
            clear_memories();
            fill_act(4096, 65536, 32, 128, 128, 16, 1'b0);
            pack_weight_ports_exp(g_q, g_q, g_s, g_s, 97, 128, 256, nt_q_stride_in, nt_s_stride_in, -8);
            pack_weight_ports_exp(u_q, u_q, u_s, u_s, 113, 128, 256, nt_q_stride_in, nt_s_stride_in, -8);
            pack_weight_ports_exp(d_q, d_q, d_s, d_s, 139, 256, 64, nt_q_stride_down, nt_s_stride_down, -4);
            init_ffn_task(66, 0, 128, 256, 64,
                          4096, 65536, 128, 16,
                          g_q, g_q, g_s, g_s,
                          u_q, u_q, u_s, u_s,
                          d_q, d_q, d_s, d_s,
                          0, 256,
                          nt_q_stride_in, nt_s_stride_in);
            program_and_start();
            wait_done("FFN_DOWN_STRIDE_KMID256_KOUT64");
            compare_ffn_generic("FFN_DOWN_STRIDE_KMID256_KOUT64", 128, 256, 64, 97, 113, 139, 0, 256, 1'b0, -8, -4);
        end
    endtask

    task automatic run_numeric_ffn_real_head(input string name,
                                             input integer task_type,
                                             input integer activation,
                                             input integer K_in,
                                             input integer K_mid,
                                             input integer N_out,
                                             input integer gate_seed,
                                             input integer up_seed,
                                             input integer down_seed,
                                             input bit varied_exp);
        integer kt_in;
        integer kt_mid;
        integer nt_mid;
        integer nt_out;
        integer act_scale_stride;
        integer nt_q_stride_in;
        integer nt_s_stride_in;
        integer nt_q_stride_down;
        integer nt_s_stride_down;
        integer g_q;
        integer g_s;
        integer u_q;
        integer u_s;
        integer d_q;
        integer d_s;
        integer out_stride;
        begin
            kt_in = div_ceil(K_in, TILE_K);
            kt_mid = div_ceil(K_mid, TILE_K);
            nt_mid = div_ceil(K_mid, SA_N);
            nt_out = div_ceil(N_out, SA_N);
            act_scale_stride = ((div_ceil(K_in, GROUP) + 15) / 16) * 16;
            nt_q_stride_in = WEIGHT_WORDS_PER_KTILE_PER_PORT * AXI_BYTES * kt_in;
            nt_s_stride_in = SCALE_WORDS_PER_KTILE_PER_PORT * AXI_BYTES * kt_in;
            nt_q_stride_down = WEIGHT_WORDS_PER_KTILE_PER_PORT * AXI_BYTES * kt_mid;
            nt_s_stride_down = SCALE_WORDS_PER_KTILE_PER_PORT * AXI_BYTES * kt_mid;
            g_q = 0;
            g_s = g_q + nt_mid * nt_q_stride_in;
            u_q = g_s + nt_mid * nt_s_stride_in;
            u_s = u_q + nt_mid * nt_q_stride_in;
            d_q = u_s + nt_mid * nt_s_stride_in;
            d_s = d_q + nt_out * nt_q_stride_down;
            out_stride = N_out * 4;

            $display("[SYS] START numeric %s", name);
            reset_dut();
            clear_memories();
            fill_act(4096, 65536, 32, K_in, K_in, act_scale_stride, varied_exp);
            // These full-shape FFN cases are structural RTL smoke tests. Keep
            // the real K/stride/tile layout, but use modest synthetic scales so
            // the checker does not turn into an INT32 saturation edge-case test.
            // Saturation behavior is not what this gate is trying to qualify.
            pack_weight_ports_exp(g_q, g_q, g_s, g_s, gate_seed, K_in, K_mid, nt_q_stride_in, nt_s_stride_in, -8);
            pack_weight_ports_exp(u_q, u_q, u_s, u_s, up_seed, K_in, K_mid, nt_q_stride_in, nt_s_stride_in, -8);
            pack_weight_ports_exp(d_q, d_q, d_s, d_s, down_seed, K_mid, N_out, nt_q_stride_down, nt_s_stride_down, -4);
            init_ffn_task(task_type, activation, K_in, K_mid, N_out,
                          4096, 65536, K_in, act_scale_stride,
                          g_q, g_q, g_s, g_s,
                          u_q, u_q, u_s, u_s,
                          d_q, d_q, d_s, d_s,
                          0, out_stride,
                          nt_q_stride_in, nt_s_stride_in);
            program_and_start();
            wait_done(name);
            compare_ffn_generic(name, K_in, K_mid, N_out, gate_seed, up_seed, down_seed, activation, out_stride, varied_exp, -8, -4);
        end
    endtask

    initial begin
        run_liveness_case(32'd64, "GEMM_DENSE_O");
        run_liveness_case(32'd65, "GEMM_FUSED_QKV");
        run_liveness_case(32'd66, "GEMM_FUSED_TEXT_FFN");
        run_liveness_case(32'd67, "GEMM_FUSED_VISION_FFN");
        $display("[SYS] PASS: ap_done liveness");

        run_numeric_dense_k768();
        run_numeric_qkv_tail_m46();
        run_numeric_ffn_stride();
        $display("[SYS] PASS: vlm_engine_v4 RTL + pe_array_v4 RTL liveness and numeric smoke");
        $finish;
    end
endmodule
