#ifndef VLM_W8A8_REGISTERS_H
#define VLM_W8A8_REGISTERS_H

#define VLM_W8A8_CONTROL_ADDR_AP_CTRL            0x00
#define VLM_W8A8_CONTROL_ADDR_GIE                0x04
#define VLM_W8A8_CONTROL_ADDR_IER                0x08
#define VLM_W8A8_CONTROL_ADDR_ISR                0x0c
#define VLM_W8A8_CONTROL_ADDR_WEIGHT0_ARENA_DATA      0x10
#define VLM_W8A8_CONTROL_ADDR_WEIGHT0_ARENA_DATA_MSB  0x14
#define VLM_W8A8_CONTROL_ADDR_WEIGHT1_ARENA_DATA      0x1c
#define VLM_W8A8_CONTROL_ADDR_WEIGHT1_ARENA_DATA_MSB  0x20
#define VLM_W8A8_CONTROL_ADDR_ACT_ARENA_DATA          0x28
#define VLM_W8A8_CONTROL_ADDR_ACT_ARENA_DATA_MSB      0x2c
#define VLM_W8A8_CONTROL_ADDR_OUT_ARENA_DATA          0x34
#define VLM_W8A8_CONTROL_ADDR_OUT_ARENA_DATA_MSB      0x38
#define VLM_W8A8_CONTROL_ADDR_TASK_OFF_DATA           0x40
#define VLM_W8A8_CONTROL_ADDR_TASK_OFF_DATA_MSB       0x44
#define VLM_W8A8_CONTROL_ADDR_PROFILE_OFF_DATA        0x4c
#define VLM_W8A8_CONTROL_ADDR_PROFILE_OFF_DATA_MSB    0x50
#define VLM_W8A8_CONTROL_ADDR_TASK_COUNT_DATA         0x58
#define VLM_W8A8_CONTROL_ADDR_STATUS_DATA             0x60
#define VLM_W8A8_CONTROL_ADDR_STATUS_CTRL             0x64

#define VLM_W8A8_CONTROL_ADDR_DATA_ARENA_DATA     VLM_W8A8_CONTROL_ADDR_ACT_ARENA_DATA
#define VLM_W8A8_CONTROL_ADDR_DATA_ARENA_DATA_MSB VLM_W8A8_CONTROL_ADDR_ACT_ARENA_DATA_MSB
#define VLM_W8A8_CONTROL_ADDR_ARENA_DATA          VLM_W8A8_CONTROL_ADDR_ACT_ARENA_DATA
#define VLM_W8A8_CONTROL_ADDR_ARENA_DATA_MSB      VLM_W8A8_CONTROL_ADDR_ACT_ARENA_DATA_MSB

#define VLM_W8A8_AP_START 0x01u
#define VLM_W8A8_AP_DONE  0x02u
#define VLM_W8A8_AP_IDLE  0x04u

#endif
